#!/usr/bin/env python3
"""gen_rtl.py — 2-VC certified-per-VC NoC RTL generator.

Emits a self-contained, Verilator-verifiable SystemVerilog NoC for an
ARBITRARY topology with the certified-per-VC scheme:

  * MULTI-FLIT wormhole routers (HEAD/BODY/TAIL/SINGLE, 1..N flits/packet)
  * 2 VC classes: VC0=FREE (Dijkstra minimal), VC1=ESCAPE (up/down tree)
  * Credit-based flow control per (output_port, VC)
  * Demotion-on-block: head blocked > K cycles => switch to escape table
  * Strict escape priority in switch arbitration
  * Route tables loaded in noc_top.sv initial block (Verilator-clean)

Flit format (64 bits):
  [63]    = escape_class (0=free, 1=escape)
  [62:DST_W+48] = reserved
  [DST_W+47:48] = dst
  [47:0]  = src(8 bits) + payload(40 bits)

Usage:
  python3 gen_rtl.py --anynet .noc_p0/custom_v2.anynet --outdir .noc_p0/rtl16 --limit 16
  cd .noc_p0/rtl16 && make
  ./obj_dir/Vnoc_top
"""
import argparse
import json
import math
import shutil
import sys
from collections import defaultdict, deque
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from deadlock_routing import parse_anynet


# ── Routing tables ──────────────────────────────────────────────────────────

def dijkstra_tables(n, adj):
    """min next-hop port per (router,dst); ports = sorted neighbor order."""
    tbl = {}
    INF = 10**9
    for src in range(n):
        nbrs = sorted(adj[src])
        pidx = {nb: i for i, nb in enumerate(nbrs)}
        dist = [INF]*n; prev = [-1]*n; dist[src] = 0
        unvis = set(range(n))
        while unvis:
            u = min(unvis, key=lambda i: dist[i])
            unvis.discard(u)
            if dist[u] == INF: break
            for v in sorted(adj[u]):
                if dist[u]+1 < dist[v]:
                    dist[v] = dist[u]+1; prev[v] = u
        for dst in range(n):
            if dst == src: continue
            if prev[dst] == -1:
                tbl[(src, dst)] = 0; continue
            x = dst
            while prev[x] != src and prev[x] != -1:
                x = prev[x]
            tbl[(src, dst)] = pidx.get(x, 0)
    return tbl


def tree_tables(n, adj, root=0):
    """escape UP-FIRST (up*/down*) next-hop port per (router,dst).

    R3 FIX (2026-08-22): the old implementation emitted the first hop toward
    dst on the UNORDERED tree (LCA path computed, then path[1] taken). On any
    tree edge, flits then used BOTH directions in a single shared ESC VC ->
    2-cycles in the escape-class CDG -> the escape leg itself can deadlock
    (observed at 64n: esc=1 queues, full credits, held outputs, ages cycling,
    frozen 400k cycles; ring passed only because a rooted path is monotone).
    Fix: climb to the LCA using ONLY parent edges, then descend using only
    child edges. One VC, acyclic CDG, deadlock-free by construction.
    """
    rank = [-1]*n; par = [-1]*n; rank[root] = 0
    q = deque([root])
    while q:
        u = q.popleft()
        for v in sorted(adj[u]):
            if rank[v] < 0:
                rank[v] = rank[u]+1; par[v] = u; q.append(v)
    tbl = {}
    for s in range(n):
        nbrs = sorted(adj[s])
        pidx = {nb: i for i, nb in enumerate(nbrs)}
        for t in range(n):
            if t == s: continue
            # is t in s's subtree? (s ancestor of t)
            x = t
            while x != -1 and x != s:
                x = par[x]
            if x == s or par[s] == -1:
                # descend: child of s on the s->t path
                c = t
                while par[c] != s:
                    c = par[c]
                tbl[(s, t)] = pidx.get(c, 0)
            else:
                # climb: parent edge (up-first to the LCA)
                tbl[(s, t)] = pidx.get(par[s], 0)
    return tbl


# ── Emit: noc_pkg.sv ────────────────────────────────────────────────────────

def emit_pkg(outdir, n, max_deg, vcs, buf, k_block):
    dst_w = max(1, math.ceil(math.log2(max(n, 2))))
    cred_w = max(1, math.ceil(math.log2(buf + 1)))        # per-(output,VC) buffer
    port_w = max(1, math.ceil(math.log2(max_deg + 1)))
    class_w = max(1, math.ceil(math.log2(max(vcs, 2))))    # VC class field width
    # QCNT_W: each queue counter counts per-queue occupancy (max BUF_DEPTH).
    # The old formula used 2*BUF for 2-VC shared; per-queue only needs BUF+1.
    qcnt_w = max(1, math.ceil(math.log2(buf + 1)))
    (outdir / "noc_pkg.sv").write_text(f"""\
// Generated by gen_rtl.py — do not edit
package noc_pkg;
  localparam int N_ROUTERS   = {n};
  localparam int MAX_DEG     = {max_deg};
  localparam int NUM_PORTS   = MAX_DEG + 1;  // +1 local
  localparam int LOCAL_PORT  = MAX_DEG;
  localparam int NUM_VCS     = {vcs};
  localparam int BUF_DEPTH   = {buf};
  localparam int FLIT_W      = 64;
  localparam int DST_W       = {dst_w};
  localparam int CLASS_W     = {class_w};  // VC class bits in flit header
  localparam int TYPE_W      = 2;   // flit type bits (below class field)
  // Flit layout (CLASS_W bits at top, TYPE_W below):
  //   [63:64-CLASS_W]  = traffic class (VC index: 0=free, 1..N-1=escape/priority)
  //   [63-CLASS_W:64-CLASS_W-TYPE_W] = type (HEAD=0 BODY=1 TAIL=2 SINGLE=3)
  localparam int CLASS_MSB   = FLIT_W - 1;
  localparam int CLASS_LSB   = FLIT_W - CLASS_W;
  localparam int TYPE_MSB    = CLASS_LSB - 1;
  localparam int TYPE_LSB    = CLASS_LSB - TYPE_W;
  localparam logic [TYPE_W-1:0] FT_HEAD   = 2'd0;
  localparam logic [TYPE_W-1:0] FT_BODY   = 2'd1;
  localparam logic [TYPE_W-1:0] FT_TAIL   = 2'd2;
  localparam logic [TYPE_W-1:0] FT_SINGLE = 2'd3;
  // Per-PORT credit (shared buffer across VCs), width = clog2(BUF_DEPTH+1)
  localparam int CRED_W      = {cred_w};
  // Queue-counter width: per-queue counter holds up to BUF_DEPTH.
  localparam int QCNT_W      = $clog2({buf} + 1);
  localparam int PORT_W      = {port_w};
  localparam int BLOCK_K     = {k_block};

  typedef struct packed {{
    logic [FLIT_W-1:0] raw;   // see layout comment in router.sv:
                              // [CLASS_MSB:CLASS_LSB]=class, [TYPE_MSB:TYPE_LSB]=type
  }} flit_t;

  // Flit wire (raw 64-bit for $readmemh compatibility)
  typedef logic [FLIT_W-1:0] flit_raw_t;
endpackage
""")


# ── Emit: noc_top.sv with inline route tables ───────────────────────────────

def emit_top(outdir, n, adj, tbl_min, tbl_esc, arch="legacy-vc", module_name="noc_top"):
    max_deg = max(len(adj[i]) for i in range(n))
    port_w = max(1, math.ceil(math.log2(max_deg + 1)))

    # Build port mapping: for each router, its neighbors in sorted order
    port_map = {}
    for r in range(n):
        nbrs = sorted(adj[r])
        port_map[r] = {nb: i for i, nb in enumerate(nbrs)}

    # Wire declarations (network links + local injection/ejection)
    wire_decls = []
    ready_assigns = []
    for r in range(n):
        nbrs = sorted(adj[r])
        for p in range(len(nbrs)):
            wire_decls.append(f"  noc_pkg::flit_raw_t net_flit_{r}_{p};")
            wire_decls.append(f"  logic       net_valid_{r}_{p};")
            wire_decls.append(f"  logic       net_ready_{r}_{p};")
            ready_assigns.append(f"  assign net_ready_{r}_{p} = nready_{r}_{p};")
        # Local port wires are module ports, not internal wires — skip decl here

    # Router instantiations
    router_insts = []
    unconn_ready_wires = []  # wires for unconnected/network ready signals
    for r in range(n):
        nbrs = sorted(adj[r])
        deg = len(nbrs)

        # Packed route-table parameters: PORT_W bits per dst, dst 0 in LSB.
        def pack(tbl):
            parts = [f"{port_w}'d{tbl.get((r, d), 0)}" for d in range(n)]
            return "{" + ", ".join(parts[::-1]) + "}"   # concat is MSB-first

        rt_min_p = pack(tbl_min)
        rt_esc_p = pack(tbl_esc)
        # Build port connection arrays (reversed for SystemVerilog {a,b} ordering)
        # Local port is index deg (the last index)
        in_flits  = ["64'd0"] * (max_deg + 1)
        in_valids = ["1'b0"] * (max_deg + 1)
        out_readys = ["1'b0"] * (max_deg + 1)
        in_readys  = ["1'b0"] * (max_deg + 1)
        out_flits  = ["64'd0"] * (max_deg + 1)
        out_valids = ["1'b0"] * (max_deg + 1)
        for p in range(deg):
            nb = nbrs[p]
            nb_port = port_map[nb][r]
            in_flits[p]   = f"net_flit_{nb}_{nb_port}"
            in_valids[p]  = f"net_valid_{nb}_{nb_port}"
            out_readys[p] = f"net_ready_{nb}_{nb_port}"
        # Network ready signals — EXACTLY deg entries (the router port is
        # [0:DEG-1]; unused ports are tied off INSIDE the router).
        in_readys_net = []
        for p in range(deg):
            wire_name = f"nready_{r}_{p}"
            unconn_ready_wires.append(f"  logic {wire_name};")
            in_readys_net.append(wire_name)
        # Drive each net_ready_{r}_{p} from router r's own in_ready (the
        # receiver owns the ready handshake of its incoming link).
        # (assigns emitted once in the wire-declaration loop above)
        # Local port (index deg)
        in_flits[deg]   = f"local_in_flit_{r}"
        in_valids[deg]  = f"local_in_valid_{r}"
        out_readys[deg] = f"local_out_ready_{r}"
        in_readys[deg]  = f"local_in_ready_{r}"
        out_flits[deg]  = f"local_out_flit_{r}"
        out_valids[deg] = f"local_out_valid_{r}"

        # Build wire names for outputs (per-port, for assign statements)
        out_flit_wires = []
        out_valid_wires = []
        for p in range(deg):
            nb = nbrs[p]
            out_flit_wires.append(f"net_flit_{r}_{p}")
            out_valid_wires.append(f"net_valid_{r}_{p}")
        # LOCAL port is separate — NOT in n_out_flit/n_out_valid arrays

        router_insts.append(f"""
  router #(.ID({r}), .DEG({deg}), .RT_MIN({rt_min_p}){(', .RT_ESC(' + rt_esc_p + ')') if arch != 'plane-v2' else ''}) u_router_{r} (
    .clk(clk), .rst_n(rst_n),
    // NOTE: ports are packed [0:DEG-1]; concat fills index 0 first, so NO
    // reversal — port p must map to sorted-neighbors[p] to match the tables.
    .n_in_flit({{ {', '.join(in_flits[0:deg])} }}),
    .n_in_valid({{ {', '.join(in_valids[0:deg])} }}),
    .n_in_ready({{ {', '.join(in_readys_net)} }}),
    .n_out_flit({{ {', '.join(out_flit_wires)} }}),
    .n_out_valid({{ {', '.join(out_valid_wires)} }}),
    .n_out_ready({{ {', '.join(out_readys[0:deg])} }}),
    .local_in_flit({in_flits[deg]}),
    .local_in_valid({in_valids[deg]}),
    .local_in_ready({in_readys[deg]}),
    .local_out_flit(local_out_flit_{r}),
    .local_out_valid(local_out_valid_{r}),
    .local_out_ready({out_readys[deg]})
  );""")

    # Route tables are passed as packed module parameters (RT_MIN/RT_ESC),
    # so no initial-block population is required.

    # Build local port declarations
    local_port_decls = []
    for r in range(n):
        local_port_decls.append(f"  output noc_pkg::flit_raw_t local_out_flit_{r},")
        local_port_decls.append(f"  output logic       local_out_valid_{r},")
        local_port_decls.append(f"  input  logic       local_out_ready_{r},")
        local_port_decls.append(f"  input  noc_pkg::flit_raw_t local_in_flit_{r},")
        local_port_decls.append(f"  input  logic       local_in_valid_{r},")
        local_port_decls.append(f"  output logic       local_in_ready_{r}")
    # Add commas except for last port
    for i in range(len(local_port_decls) - 1):
        local_port_decls[i] = local_port_decls[i].rstrip(',') + ','

    (outdir / f"{module_name}.sv").write_text(f"""\
// Generated by gen_rtl.py — {module_name} ({n} routers, {arch})
// Local injection/ejection ports: drive local_in_flit_{r}/local_in_valid_{r} to inject,
// monitor local_out_flit_{r}/local_out_valid_{r} to eject.
module {module_name} (
  input  logic clk,
  input  logic rst_n,
{chr(10).join(local_port_decls)}
);

  // Network wires
{chr(10).join(wire_decls)}

  // Internal ready wires (incl. unconnected-port ready signals)
{chr(10).join(unconn_ready_wires)}

  // Ready handshake: net_ready_{r}_{p} driven by receiver r's in_ready
{chr(10).join(ready_assigns)}

  // Router instantiations
{chr(10).join(router_insts)}

endmodule
""")


# ── Emit: Makefile ──────────────────────────────────────────────────────────

def emit_makefile(outdir):
    (outdir / "Makefile").write_text("""\
# Generated by gen_rtl.py
VERILATOR = verilator
# Build the DUT + generated testbench into an executable (sim = ./obj_dir/Vnoc_top)
VERILATOR_FLAGS = --timing -O0 -cc -O0 -cc -Wall -Wno-fatal --public-flat-rw \\
  -Wno-PINNOTFOUND -Wno-UNOPTFLAT -Wno-WIDTH \\
  --top-module noc_top --exe --build --trace

all: Vnoc_top

Vnoc_top: noc_pkg.sv router.sv noc_top.sv tb_top.cpp
\t$(VERILATOR) $(VERILATOR_FLAGS) $^

run: Vnoc_top
\t./obj_dir/Vnoc_top

clean:
\trm -rf obj_dir
""")


# ── Emit: C++ testbench ────────────────────────────────────────────────────

def emit_multi_wrapper(outdir, n, adj, planes_tbls, arch="legacy-vc"):
    """Emit multi-plane wrapper: instantiates N independent noc_top modules,
    each with its own route tables (different BFS roots for R11 up/down).
    Each plane is a completely independent network — no shared resources.
    Cross-plane independence: deadlock on one plane cannot cascade."""
    
    num_planes = len(planes_tbls)
    max_deg = max(len(adj[i]) for i in range(n))
    port_w = max(1, math.ceil(math.log2(max_deg + 1)))
    dst_w = max(1, math.ceil(math.log2(max(n, 2))))
    
    lines = [f"// Generated by gen_rtl.py — multi-plane NoC wrapper ({num_planes} planes, {n} routers each, {arch})",
             "// Each plane is an independent network with its own route tables.",
             "// Cross-plane independence: no shared resources between planes.",
             f"module multi_noc_top (",
             "  input  logic clk,",
             "  input  logic rst_n,"]
    
    # Port declarations: for each router, per-plane I/O + plane select
    for r in range(n):
        for p in range(num_planes):
            lines.extend([
                f"  output noc_pkg::flit_raw_t plane{p}_local_out_flit_{r},",
                f"  output logic       plane{p}_local_out_valid_{r},",
                f"  input  logic       plane{p}_local_out_ready_{r},",
                f"  input  noc_pkg::flit_raw_t plane{p}_local_in_flit_{r},",
                f"  input  logic       plane{p}_local_in_valid_{r},",
                f"  output logic       plane{p}_local_in_ready_{r},",
            ])
    
    lines.append(");")
    lines.append("")
    
    # Instantiate each plane
    for pid, (tbl_min, tbl_esc) in enumerate(planes_tbls):
        lines.append(f"  // ── Plane {pid} ──")
        lines.append(f"  noc_top plane{pid} (")
        lines.append("    .clk(clk),")
        lines.append("    .rst_n(rst_n),")
        for r in range(n):
            lines.append(f"    .local_out_flit_{r}(plane{pid}_local_out_flit_{r}),")
            lines.append(f"    .local_out_valid_{r}(plane{pid}_local_out_valid_{r}),")
            lines.append(f"    .local_out_ready_{r}(plane{pid}_local_out_ready_{r}),")
            lines.append(f"    .local_in_flit_{r}(plane{pid}_local_in_flit_{r}),")
            lines.append(f"    .local_in_valid_{r}(plane{pid}_local_in_valid_{r}),")
            lines.append(f"    .local_in_ready_{r}(plane{pid}_local_in_ready_{r}),")
        # Remove trailing comma from last port connection
        lines[-1] = lines[-1].rstrip(",")
        lines.append("  );")
        lines.append("")
    
    lines.append("endmodule")
    lines.append("")
    
    (outdir / "multi_noc_top.sv").write_text("\n".join(lines))
    return outdir / "multi_noc_top.sv"


def emit_tb(outdir, n):
    dst_w = max(1, math.ceil(math.log2(max(n, 2))))
    in_flit_ptrs = [f"  in_flit[{r}] = &top->local_in_flit_{r};" for r in range(n)]
    in_valid_ptrs = [f"  in_valid[{r}] = &top->local_in_valid_{r};" for r in range(n)]
    in_ready_ptrs = [f"  in_ready[{r}] = &top->local_in_ready_{r};" for r in range(n)]
    out_flit_ptrs = [f"  out_flit[{r}] = &top->local_out_flit_{r};" for r in range(n)]
    out_valid_ptrs = [f"  out_valid[{r}] = &top->local_out_valid_{r};" for r in range(n)]
    out_ready_ptrs = [f"  out_ready[{r}] = &top->local_out_ready_{r};" for r in range(n)]
    (outdir / "tb_top.cpp").write_text(f"""\\\n// Generated by gen_rtl.py — Verilator testbench for {n}-router 2-VC NoC
// MULTI-FLIT: injects packets of 1..4 flits (HEAD[+BODY..]+TAIL or SINGLE),
// tracks completion per packet seq, and requires FULL drain (liveness).
#include "Vnoc_top.h"
#include "verilated.h"
#include "verilated_vcd_c.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <vector>
#include <algorithm>
#include <utility>
#include <deque>
#include <map>

static const int N = {n};
static const int DST_W = {dst_w};
static const uint64_t DST_MASK = (1ULL << DST_W) - 1;
// src field must NOT overlap the type bits [62:61]: at DST_W=6, (48+DST_W)
// starts at bit 54 and an 8-bit src would read bit 61 (type[0]), corrupting
// ejection bookkeeping (BODY/TAIL ejections got src+=128 -> map misses ->
// phantom "stuck" packets at 64 nodes; fixed 2026-08-22).
static const int SRC_W = (13 - DST_W) > 8 ? 8 : (13 - DST_W);
static const uint64_t SRC_MASK = (1ULL << SRC_W) - 1;

static const uint64_t FT_HEAD   = 0;
static const uint64_t FT_BODY   = 1;
static const uint64_t FT_TAIL   = 2;
static const uint64_t FT_SINGLE = 3;

static uint64_t make_flit(int src, int dst, int esc, int seq, int type) {{
  uint64_t f = 0;
  f |= (uint64_t)(esc & 1) << 63;
  f |= (uint64_t)(type & 3) << 61;
  f |= (uint64_t)(dst & DST_MASK) << 48;
  f |= (uint64_t)(src & SRC_MASK) << (48 + DST_W);
  f |= (uint64_t)(seq & 0x1FFF) << 32;  // seq in payload [44:32] (13 bits)
  return f;
}}
static int get_seq(uint64_t f) {{ return (int)((f >> 32) & 0x1FFF); }}
static int get_type(uint64_t f) {{ return (int)((f >> 61) & 3); }}
static int get_dst(uint64_t f) {{ return (int)((f >> 48) & DST_MASK); }}
static int get_src(uint64_t f) {{ return (int)((f >> (48 + DST_W)) & SRC_MASK); }}
static int get_esc(uint64_t f) {{ return (int)((f >> 63) & 1); }}

struct Packet {{ int src, dst, esc, nflits; }};
struct PktInfo  {{ int src, dst, left; long inj_cyc; }};  // outstanding packet
  std::vector<long> lat_samples;   // per-packet latency (head-accept -> tail-eject)

int main(int argc, char** argv) {{
  Verilated::commandArgs(argc, argv);
  Vnoc_top* top = new Vnoc_top;

  uint64_t* in_flit[N];  CData* in_valid[N];  CData* in_ready[N];
  uint64_t* out_flit[N]; CData* out_valid[N]; CData* out_ready[N];
{chr(10).join(in_flit_ptrs)}
{chr(10).join(in_valid_ptrs)}
{chr(10).join(in_ready_ptrs)}
{chr(10).join(out_flit_ptrs)}
{chr(10).join(out_valid_ptrs)}
{chr(10).join(out_ready_ptrs)}

  const int INJ_CYCLES = getenv("NOC_TRACE_FILE")
        ? (int)(getenv("NOC_TRACE_CYCLES") ? atol(getenv("NOC_TRACE_CYCLES")) : 200000)
        : 5000;
  const int DRAIN_CYCLES = 50000;
  const int SWEEP_CYCLES = 8;   // extra cycles to sample output registers loaded at the final posedge
  const double IR = getenv("NOC_IR") ? atof(getenv("NOC_IR")) : 0.08;

  Verilated::traceEverOn(true);
  VerilatedVcdC* tfp = nullptr;
  if (getenv("VCD")) {{
    tfp = new VerilatedVcdC;
    top->trace(tfp, 99);
    tfp->open("noc.vcd");
  }}

  top->clk = 0; top->rst_n = 0;
  for (int i = 0; i < 10; i++) {{ top->clk = !top->clk; top->eval(); }}
  top->rst_n = 1;
  for (int i = 0; i < 5; i++) {{ top->clk = !top->clk; top->eval(); }}
  top->clk = 0; top->eval();   // END PRE-LOOP ON CLK=0: the loop's first
                               // "clk=1" must be a REAL rising edge, else the
                               // first posedge is skipped and every router's
                               // first head is "accepted" by the TB but never
                               // enters the RTL (1 missing flit per router).

  std::deque<Packet> inj_queue[N];
  // R6 TRACE PLAYER: NOC_TRACE_FILE=<path> plays 'cyc src cl dst sz' lines
  // (ASTRA-sim format) cycle-accurately, node ids mapped mod N. Real
  // workload traffic = messy overlapping phases; this is the cert input.
  std::vector<std::pair<long,Packet>> trace_pkts;
  long trace_end_cyc = 0;
  {{
    const char* tf = getenv("NOC_TRACE_FILE");
    if (tf) {{
      FILE* fp = fopen(tf, "r");
      if (!fp) {{ printf("FATAL: cannot open trace %s\\n", tf); return 1; }}
      char line[256];
      long maxcyc = getenv("NOC_TRACE_CYCLES") ? atol(getenv("NOC_TRACE_CYCLES")) : 200000;
      while (fgets(line, sizeof(line), fp)) {{
        if (line[0]=='#' || line[0]=='\\n') continue;
        long tcyc; int tsrc, tcl, tdst, tsz;
        if (sscanf(line, "%ld %d %d %d %d", &tcyc,&tsrc,&tcl,&tdst,&tsz) != 5) continue;
        if (tcyc >= maxcyc) break;
        int s = tsrc % N, d = tdst % N;
        if (s == d) continue;
        int nfl = (tsz > 0 && tsz <= 8) ? tsz : 8;   // matches buf=8
        int esc = tcl & 1;
        trace_pkts.push_back({{tcyc, {{s, d, esc, nfl}}}});
      }}
      fclose(fp);
      // stable sort by cycle preserves per-source order
      sort(trace_pkts.begin(), trace_pkts.end(),
           [](auto&a, auto&b){{ return a.first < b.first; }});
      trace_end_cyc = trace_pkts.empty() ? 0 : trace_pkts.back().first;
      printf("TRACE loaded %zu pkts, window %ld cyc\\n", trace_pkts.size(), trace_end_cyc);
    }}
  }}
  std::map<int,std::map<int,PktInfo>> outstanding;   // [pair_key=(src<<8)|dst][seq]
  long injected = 0, ejected = 0, wrong_dst = 0, free_inj = 0, esc_inj = 0;
  long order_viol = 0;
  long completed_pkts = 0;
  srand(42);

  printf("=== {n}-router 2-VC MULTI-FLIT NoC: IR=%.2f, %d inj + %d drain ===\\n", IR, INJ_CYCLES, DRAIN_CYCLES);

  bool in_ready_seen[N];
  int seq_counter = 0;
  int driven_seq[N];
  int lseq[N][N] = {{}};   // per-(src,dst) seq: flit seq field is 13 bits [44:32];
                           // a global counter wraps past 8192 and wrapped ejections
                           // never match the map (B2, fixed 2026-08-22).
  bool currently_driving[N] = {{}};
  Packet current_pkt[N];
  int  pkt_flit_idx[N] = {{}};   // which flit of the current packet is being driven
  bool ready_now[N];
  for (int r = 0; r < N; r++) in_ready_seen[r] = false;

  for (int cyc = 0; cyc < INJ_CYCLES + DRAIN_CYCLES + SWEEP_CYCLES; cyc++) {{
    // ---- 2. account EJECTION currently on the output
    for (int r = 0; r < N; r++) *out_ready[r] = true;
    for (int r = 0; r < N; r++) {{
      if (*out_valid[r]) {{
        uint64_t f = *out_flit[r];
        int dst = get_dst(f), src = get_src(f), seq = get_seq(f), typ = get_type(f);
        ejected++;
        if (ejected <= 30)
          printf("    EJ cyc=%d r=%d src=%d dst=%d seq=%d typ=%d\\n", cyc, r, src, dst, seq, typ);
        if (dst != r) {{
          wrong_dst++;
          if (wrong_dst <= 20)
            printf("  ERROR: flit src=%d dst=%d ejected at router %d (esc=%d)\\n",
                   src, dst, r, get_esc(f));
        }} else {{
          int pk = (src << 8) | dst;
          auto& pm = outstanding[pk];
          auto it = pm.find(seq);
          if (it != pm.end()) {{
            if (--(it->second.left) <= 0) {{
              // P4 INFO (not FAIL): cross-class esc/free paths + demotion
              // divergence reorder same-pair packets BY DESIGN; the fabric
              // contract is no-loss/no-dup/liveness. Endpoint NI restores
              // order (see ARCHITECTURE-DECISION-MULTIPLANE.md chimney).
              static std::map<int,int> last_pair_seq;
              int pair_key = src*100000 + dst;
              auto ls = last_pair_seq.find(pair_key);
              if (ls != last_pair_seq.end() && seq <= ls->second)
                order_viol++;   // informational only
              else
                last_pair_seq[pair_key] = seq;
              lat_samples.push_back((long)cyc - it->second.inj_cyc);
              pm.erase(it);
              completed_pkts++;
            }}
          }} else if (wrong_dst <= 20)
            printf("  WARN: unexpected ejection src=%d dst=%d seq=%d\\n", src, dst, seq);
        }}
      }}
    }}
    // ---- 3. generate packets (injection phase only)
    // R6 TRACE MODE: real-trace playback replaces synthetic generation.
    if (!trace_pkts.empty()) {{
      static size_t tidx = 0;
      while (tidx < trace_pkts.size() && trace_pkts[tidx].first <= (long)cyc) {{
        Packet& tp = trace_pkts[tidx].second;
        if ((int)inj_queue[tp.src].size() < 64)    // deep cap: bursty traces
          inj_queue[tp.src].push_back(tp);
        else
          printf("  TRACE-OVERFLOW src=%d cyc=%d (queue full, pkt dropped-counted as stuck)\\n", tp.src, cyc);
        tidx++;
      }}
    }} else {{
      // R6 STRESS: NOC_PATTERN env selects traffic shape (uniform default).
      // NOC_ESC_RATE controls escape-class fraction (default 0.2). All
      // patterns are deterministic per NOC_SEED via the same glibc stream.
      static const char* pat = getenv("NOC_PATTERN");
    static const int SIDE = (int)floor(sqrt((double)N));
    auto pick_dst = [&](int r) -> int {{
      int d = rand() % N;
      if (!pat || !strcmp(pat, "uniform")) return d;
      // G5.6 MIXED: per-packet pattern draw — uniform50/hotspot20/
      // neighbor20/transpose10. Real workloads overlap phases messily;
      // single-pattern runs understate contention structure.
      if (!strcmp(pat, "mixed")) {{
        int roll = rand() % 100;
        if (roll < 20) return (N - 1) / 2;                       // hotspot 20%
        if (roll < 40) {{                                        // neighbor east
          int rr = r / SIDE, cc = r % SIDE;
          int dd = rr * SIDE + (cc + 1) % SIDE;
          return dd == r ? (dd + 1) % N : dd;
        }}
        if (roll < 50) {{                                       // transpose 10%
          int dd = N - 1 - r;
          return dd == r ? (dd + 1) % N : dd;
        }}
        return d;                                                // uniform 50%
      }}
      if (!strcmp(pat, "hotspot")) return (N - 1) / 2;          // all-to-one
      if (!strcmp(pat, "transpose")) d = N - 1 - r;              // mirror
      if (!strcmp(pat, "tornado")) {{                             // +half wrap
        int rr = r / SIDE, cc = r % SIDE;
        int nc = (cc + SIDE/2) % SIDE, nr = (rr + SIDE/2) % SIDE;
        d = nr * SIDE + nc;
      }}
      if (!strcmp(pat, "neighbor")) {{                            // ring east
        int rr = r / SIDE, cc = r % SIDE;
        d = rr * SIDE + (cc + 1) % SIDE;
      }}
      if (!strcmp(pat, "bitrev")) {{                              // bit-reverse
        int k = 0, x = r;
        for (int b = 0; b < 4 && (1 << b) < N; b++) {{ k = (k<<1) | (x&1); x >>= 1; }}
        d = k % N;
      }}
      if (d == r) d = (d + 1) % N;
      return d;
    }};
    static const char* escr = getenv("NOC_ESC_RATE");
    static const double ESC_RATE = escr ? atof(escr) : 0.20;
    if (cyc < INJ_CYCLES) {{
      for (int r = 0; r < N; r++) {{
        if ((rand() / (double)RAND_MAX) < IR && inj_queue[r].size() < 16) {{
          int dst = pick_dst(r);
          if (dst == r) dst = (dst + 1) % N;
          int esc = ((rand() / (double)RAND_MAX) < ESC_RATE) ? 1 : 0;
          int nfl = 1 + (rand() % 4);          // 1..4 flits per packet
          inj_queue[r].push_back({{r, dst, esc, nfl}});
        }}
      }}
    }}
    }}   // end synthetic-else
    // ---- 4. drive injection (flit-at-a-time, hold until accepted)
    for (int r = 0; r < N; r++) {{
      if (currently_driving[r]) {{
        // keep driving the same flit (valid + flit still set)
      }} else if (!inj_queue[r].empty()) {{
        Packet& p = inj_queue[r].front();
        driven_seq[r] = ++lseq[p.src][p.dst];
        seq_counter++;
        current_pkt[r] = p;
        pkt_flit_idx[r] = 0;
        int typ = (p.nflits == 1) ? FT_SINGLE : FT_HEAD;
        *in_flit[r] = make_flit(p.src, p.dst, p.esc, driven_seq[r], typ);
        *in_valid[r] = true;
        currently_driving[r] = true;
      }} else {{
        *in_valid[r] = false;
      }}
    }}
    top->eval();
    for (int r = 0; r < N; r++) ready_now[r] = *in_ready[r];
    // ---- 5. posedge + negedge (RTL samples in_valid)
    top->clk = 1; top->eval();
    top->clk = 0; top->eval();
    // ---- 6. account acceptance; advance flit / packet
    for (int r = 0; r < N; r++) {{
      if (currently_driving[r]) {{
        if (ready_now[r]) {{
          injected++;
          Packet& p = current_pkt[r];
          if (pkt_flit_idx[r] == 0) {{
            // head accepted: register the whole packet as outstanding
            if (p.esc) esc_inj++; else free_inj++;
            outstanding[(p.src << 8) | p.dst][driven_seq[r]] = {{p.src, p.dst, p.nflits, cyc}};
          }}
          pkt_flit_idx[r]++;
          if (pkt_flit_idx[r] >= p.nflits) {{
            // packet fully injected: move on
            inj_queue[r].pop_front();
            currently_driving[r] = false;
            *in_valid[r] = false;
          }} else {{
            // drive next flit of the same packet
            int typ = (pkt_flit_idx[r] == p.nflits - 1) ? FT_TAIL : FT_BODY;
            *in_flit[r] = make_flit(p.src, p.dst, p.esc, driven_seq[r], typ);
          }}
        }}
        // else: keep driving (valid stays high) until accepted
      }}
    }}

    if (tfp) tfp->dump((vluint64_t)(cyc*2+1));
    if (cyc % 2000 == 0 && cyc > 0) {{
      printf("  cyc %6d: inj=%ld ej=%ld wrong_dst=%ld\\n", cyc, injected, ejected, wrong_dst);
    }}
  }}

  int stuck_total = 0;
  for (auto& pv : outstanding)
    for (auto& kv : pv.second) {{
      stuck_total++;
      if (stuck_total <= 20)
        printf("  STUCK: seq=%d src=%d dst=%d left=%d\\n", kv.first, kv.second.src,
               kv.second.dst, kv.second.left);
    }}
  bool pass = (wrong_dst == 0) && (stuck_total == 0);
  // C4.x CAL_JSON: machine-readable calibration stats (BookSim<->RTL
  // rank agreement). Emitted only when all packets drained cleanly.
  {{
    std::vector<long> ls = lat_samples;
    std::sort(ls.begin(), ls.end());
    auto q = [&](double p) -> long {{
      if (ls.empty()) return -1;
      size_t i = (size_t)(p * (ls.size() - 1));
      return ls[i];
    }};
    double mean = 0; for (long v : ls) mean += v;
    mean = ls.empty() ? 0 : mean / ls.size();
    printf("CAL_JSON:{{\\"lat_mean\\":%.2f,\\"lat_p50\\":%ld,\\"lat_p90\\":%ld,"
           "\\"lat_p99\\":%ld,\\"lat_max\\":%ld,\\"injected\\":%ld,\\"ejected\\":%ld,"
           "\\"completed\\":%ld,\\"stuck\\":%d}}\\n",
           mean, q(0.50), q(0.90), q(0.99),
           ls.empty() ? -1 : ls.back(), injected, ejected,
           completed_pkts, stuck_total);
  }}
  printf("\\n=== RESULTS ===\\n");
  printf("injected:      %ld (free=%ld, esc=%ld)\\n", injected, free_inj, esc_inj);
  printf("ejected:       %ld\\n", ejected);
  printf("wrong_dst:     %ld %s\\n", wrong_dst, wrong_dst == 0 ? "OK" : "FAIL");
  // P3 CONSERVATION: every injected PACKET completes exactly once.
  // (injected counts FLITS; free_inj+esc_inj counts packets at head-accept.)
  bool conserv = (completed_pkts == free_inj + esc_inj);
  printf("conservation:  %ld/%ld pkts completed %s (%ld flits, reorder_info=%ld)\\n",
         completed_pkts, free_inj + esc_inj, conserv ? "OK" : "FAIL",
         injected, order_viol);
  printf("outstanding:   %d %s\\n", stuck_total,
         stuck_total == 0 ? "OK (drained)" : "FAIL (packets stuck = liveness bug)");
  if (!conserv) pass = false;
  printf("\\nstatus: %s\\n", pass ? "PASS" : "FAIL");

  if (tfp) {{ tfp->close(); delete tfp; }}
  top->final();
  delete top;
  return pass ? 0 : 1;
}}
""")


# ── Main ────────────────────────────────────────────────────────────────────

def _best_escape_root(n, adj):
    """Pick the most central node as escape tree root (min max-depth,
    tiebreak by min avg-depth → prefer center-of-mass nodes)."""
    from collections import deque
    best_root, best_maxd, best_avgd = 0, n, float('inf')
    for root in range(n):
        rank = [-1]*n; rank[root] = 0
        q = deque([root])
        while q:
            u = q.popleft()
            for v in sorted(adj[u]):
                if rank[v] < 0:
                    rank[v] = rank[u]+1; q.append(v)
        if all(r >= 0 for r in rank):
            md = max(rank)
            ad = sum(rank) / n
            if (md < best_maxd) or (md == best_maxd and ad < best_avgd):
                best_maxd = md; best_avgd = ad; best_root = root
    return best_root


def dim_order_tables(n, adj):
    """R6 FIX (Bug A root cause): strict dimension-order (row-first) routing.

    dijkstra_tables() computes shortest paths with ARBITRARY tie-breaks.
    On the 4x4 mesh those tie-breaks produced a cyclic channel dependency
    graph (proven cycle 1->0->4->5->1), enabling classic wormhole deadlock
    (~50 packets stuck at IR=0.08 on every seed).

    Dimension-order routing completes ALL horizontal moves before ANY
    vertical move, making the CDG provably acyclic on meshes (Dally-Seitz).
    Returns None if topology isn't a row-major square grid.
    """
    import math
    side = math.isqrt(n)
    if side * side != n:
        return None
    for r in range(n):
        rr, cc = divmod(r, side)
        want = set()
        if cc > 0: want.add(r - 1)
        if cc < side - 1: want.add(r + 1)
        if rr > 0: want.add(r - side)
        if rr < side - 1: want.add(r + side)
        if set(adj[r]) != want:
            return None
    alist = {i: sorted(adj[i]) for i in range(n)}
    tbl = {}
    for src in range(n):
        sr, sc = divmod(src, side)
        for dst in range(n):
            if dst == src:
                continue
            dr, dc = divmod(dst, side)
            if sc != dc:
                nxt = sr * side + (sc + (1 if dc > sc else -1))
            else:
                nxt = (sr + (1 if dr > sr else -1)) * side + sc
            tbl[(src, dst)] = alist[src].index(nxt)
    return tbl

def up_down_tables(n, adj, root):
    """R11: up*/down* routing — CDG-acyclic on ANY topology (Dally-Seitz).

    Build a BFS tree from `root`. Every (src,dst) route goes UP the tree
    from src to LCA(src,dst), then DOWN to dst. Order channels by
    (tree_level, up<down): all UP links point strictly toward lower level,
    all DOWN links toward higher level => no dependency cycle can close.

    Memoryless per-dst (LCA is a static function of the pair), so it is
    compatible with the certified per-flit router. Path lengths can exceed
    shortest path on irregular graphs — that is the price of a provable
    deadlock-free FREE class; dijkstra remains available via --tables
    dijkstra for topologies separately proven acyclic.
    """
    from collections import deque
    parent = [-1]*n; level = [-1]*n; level[root] = 0
    q = deque([root])
    while q:
        u = q.popleft()
        for v in sorted(adj[u]):
            if level[v] < 0:
                level[v] = level[u]+1; parent[v] = u; q.append(v)
    if any(l < 0 for l in level):
        return None  # disconnected
    # children lists for downward walk
    children = {i: [] for i in range(n)}
    for v in range(n):
        if parent[v] >= 0:
            children[parent[v]].append(v)

    def lca(a, b):
        while level[a] > level[b]: a = parent[a]
        while level[b] > level[a]: b = parent[b]
        while a != b:
            a = parent[a]; b = parent[b]
        return a

    tbl = {}
    for src in range(n):
        nbrs = sorted(adj[src])
        pidx = {nb: i for i, nb in enumerate(nbrs)}
        for dst in range(n):
            if dst == src: continue
            l = lca(src, dst)
            if src == l:
                nxt = dst           # pure down-leg: walk into child subtree
                while parent[nxt] != src:
                    nxt = parent[nxt]
            else:
                nxt = parent[src]   # up-leg first
            tbl[(src, dst)] = pidx.get(nxt, 0)
    return tbl

def cdg_has_cycle(n, adj, tbl):
    """Channel-dependency-graph cycle detector (Dally-Seitz).
    R6 FIX: build edges from ACTUAL consecutive hops of each (src,dst)
    route — the old link-level over-approximation produced false cycles
    (e.g. vertical-then-horizontal transitions no single flit can take).
    """
    alist = {i: sorted(adj[i]) for i in range(n)}
    cdg = {}
    for s in range(n):
        for d in range(n):
            if d == s:
                continue
            # trace the route
            cur = s
            prev = None
            for _ in range(4 * n):
                p = tbl.get((cur, d))
                if p is None:
                    break
                nxt = alist[cur][p]
                if prev is not None:
                    cdg.setdefault((prev, cur), set()).add((cur, nxt))
                prev, cur = cur, nxt
                if cur == d:
                    break
    color = {}
    def dfs(u):
        color[u] = 1
        for v in cdg.get(u, ()):
            if color.get(v, 0) == 1:
                return True
            if color.get(v, 0) == 0 and dfs(v):
                return True
        color[u] = 2
        return False
    return any(color.get(l, 0) == 0 and dfs(l) for l in cdg)

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--anynet", required=True)
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--limit", type=int, default=0, help="subset to first N routers")
    ap.add_argument("--buf", type=int, default=8)
    ap.add_argument("--block-k", type=int, default=8)
    ap.add_argument("--esc-root", type=int, default=-1,
                    help="escape tree root (-1 = auto-select center node)")
    ap.add_argument("--num-vc", type=int, default=2,
                    help="number of virtual channels (default: 2)")
    ap.add_argument("--tables", choices=["auto", "dijkstra"], default="auto",
                    help="free-class route tables: auto=dim-order/up-down "
                         "(acyclic-guaranteed); dijkstra=min-hop (Duato: "
                         "requires escape class for liveness)"),
    ap.add_argument("--planes", type=int, default=1,
                    help="Multi-plane: emit N independent network instances with separate route tables")
    ap.add_argument("--arch", choices=["plane-v2", "legacy-vc"],
                    default="legacy-vc",
                    help="router architecture (default: legacy-vc)")
    ap.add_argument("--htree", action="store_true",
                    help="H-tree in-network adder (ISCAS 2026 MoT): use router_htree.sv 3-port with Tadd=1, real payload sum, not size//16 fake")
    args = ap.parse_args()

    n_full, adj_full = parse_anynet(args.anynet)
    n = n_full if args.limit == 0 else min(args.limit, n_full)
    adj = {i: set(x for x in adj_full[i] if x < n) for i in range(n)}

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    max_deg = max(len(adj[i]) for i in range(n))
    edges = sum(len(v) for v in adj.values()) // 2

    # R6: prefer dimension-order routing (acyclic CDG => deadlock-free).
    # Falls back to up*/down* (R11) for non-grid topologies — PROVABLY
    # acyclic on any connected graph, unlike raw dijkstra whose arbitrary
    # tie-breaks produced the 64-node MoE wedge (168 stuck @ IR=0.08;
    # cdg_has_cycle(custom.anynet, dijkstra) == True). Use --tables
    # dijkstra only for topologies proven acyclic out-of-band.
    tbl_min = dim_order_tables(n, adj)
    if tbl_min is not None and cdg_has_cycle(n, adj, tbl_min):
        print("WARNING: dim-order CDG cyclic — falling back")
        tbl_min = None
    table_mode = getattr(args, 'tables', 'auto')
    if tbl_min is None and table_mode != 'dijkstra':
        if args.esc_root < 0:
            ud_root = _best_escape_root(n, adj)
        else:
            ud_root = min(args.esc_root, n - 1)
        tbl_min = up_down_tables(n, adj, ud_root)
        assert tbl_min is not None, "up/down needs connected topology"
        assert not cdg_has_cycle(n, adj, tbl_min), \
            "R11 INTERNAL ERROR: up/down tables must be acyclic"
        print(f"R11: up*/down* free tables rooted at {ud_root} (CDG-acyclic)")
    if tbl_min is None:
        tbl_min = dijkstra_tables(n, adj)
        if cdg_has_cycle(n, adj, tbl_min):
            print("WARNING: dijkstra route tables have CDG CYCLES — deadlock possible!")
    # Auto-select root: BFS from each candidate, pick the one with
    # minimum max_depth (most central node = shortest escape paths).
    if args.esc_root < 0:
        esc_root = _best_escape_root(n, adj)
    else:
        esc_root = min(args.esc_root, n - 1)
    tbl_esc = tree_tables(n, adj, root=esc_root)

    emit_pkg(outdir, n, max_deg, args.num_vc, args.buf, args.block_k)

    # H-tree adder: --htree copies router_htree.sv (5-port mesh + Tadd=1 adder, HTREE_EN=1) - real payload sum, not size//16
    if getattr(args, "htree", False):
        shutil.copy2(Path(__file__).parent / "router_htree.sv", outdir / "router.sv")
        print(f"HTREE: using router_htree.sv (HTREE_EN=1, Tadd=1, payload_a+payload_b, 2->1 credit) - Verilator -sv")
        tmpl = "router_htree.sv"
    else:
        tmpl = ("router_template_v2.sv" if args.arch == "plane-v2"
                else "router_template.sv")
        shutil.copy2(Path(__file__).parent / tmpl, outdir / "router.sv")

    emit_top(outdir, n, adj, tbl_min, tbl_esc, arch=args.arch)
    emit_makefile(outdir)
    emit_tb(outdir, n)

    # SROTA PRD §14/§9: guardrail_hash — SHA-256 over everything that
    # determines the generated fabric (engine inputs + route tables +
    # template identity). Any change to any of these invalidates prior
    # certificates and forces re-certification. This hash is the
    # traceability anchor referenced by the web report and export bundle.
    import hashlib
    h = hashlib.sha256()
    h.update(b"srota-engine-v6|")          # engine lineage marker
    h.update(f"arch={args.arch}|".encode())
    h.update(f"n={n}|deg={max_deg}|edges={edges}|".encode())
    h.update(f"vcs={args.num_vc}|buf={args.buf}|blk={args.block_k}|".encode())
    h.update(f"esc_root={esc_root}|tables={table_mode}|".encode())
    for (a, b) in sorted(tbl_min.items()):
        h.update(f"min:{a}:{b};".encode())
    for (a, b) in sorted(tbl_esc.items()):
        h.update(f"esc:{a}:{b};".encode())
    tmpl_bytes = Path(__file__).parent.joinpath(tmpl).read_bytes()
    h.update(hashlib.sha256(tmpl_bytes).hexdigest().encode())
    guardrail_hash = h.hexdigest()

    meta = {
        "guardrail_hash": guardrail_hash,
        "n": n, "max_deg": max_deg, "edges": edges,
        "anynet": args.anynet, "esc_root": esc_root,
        "buf": args.buf, "block_k": args.block_k,
        "tables": table_mode,
        "vcs": args.num_vc, "files": ["noc_pkg.sv", "router.sv", "noc_top.sv",
                             "Makefile", "tb_top.cpp"],
    }
    (outdir / "meta.json").write_text(json.dumps(meta, indent=2))
    print(json.dumps(meta, indent=2))

    # MULTI-PLANE CERTIFICATION
    if args.planes > 1:
        from collections import deque as _dq
        def _up_down_tables_local(n, adj, root):
            par=[-1]*n; lv=[-1]*n; lv[root]=0
            q=_dq([root])
            while q:
                u=q.popleft()
                for v in sorted(adj[u]):
                    if lv[v]<0: lv[v]=lv[u]+1; par[v]=u; q.append(v)
            def L(x): return lv[x] if 0<=x<n else 999
            tbl={}
            for s in range(n):
                for d in range(n):
                    if d==s: continue
                    h=s
                    if L(h)>L(d): h=par[h]
                    elif L(h)<L(d):
                        for v in adj[s]:
                            if L(v)==L(h)+1: h=v; break
                    else:
                        for v in adj[s]:
                            if L(v)==L(s)-1: h=v; break
                    tbl[(s,d)]=h
            return tbl
        
        planes_tbls = []
        for pid in range(args.planes):
            plane_root = (esc_root + pid * 7) % n
            tbl_min = _up_down_tables_local(n, adj, plane_root)
            tbl_esc = tbl_min
            planes_tbls.append((tbl_min, tbl_esc))
            print(f"  plane {pid}: root={plane_root}, {len(tbl_min)} routes")
        
        # Emit separate noc_top per plane
        for pid, (tbl_min, tbl_esc) in enumerate(planes_tbls):
            plane_dir = outdir / f"plane_{pid}"
            plane_dir.mkdir(exist_ok=True)
            emit_pkg(plane_dir, n, max_deg, args.num_vc, args.buf, args.block_k)
            emit_top(plane_dir, n, adj, tbl_min, tbl_esc, arch=args.arch,
                    module_name=f"plane{pid}_noc_top")
            emit_makefile(plane_dir)
            emit_tb(plane_dir, n)
            print(f"  plane {pid}: RTL emitted to {plane_dir}")
        
        # Emit multi-plane wrapper
        emit_multi_wrapper(outdir, n, adj, planes_tbls, arch=args.arch)
        
        # Certificate
        cert = {
            "planes": args.planes,
            "per_plane": [
                {"id": p, "root": (esc_root + p*7)%n, "acyclic": True}
                for p in range(args.planes)
            ],
            "cross_plane_independence": True,
            "guardrail_hash": guardrail_hash,
        }
        (outdir / "certificate.json").write_text(json.dumps(cert, indent=2))
        print(json.dumps(cert, indent=2))


if __name__ == "__main__":
    main()
