"""SCHEMA 3 IS FROZEN — non-regression proof (PHASE B.1 §3, §25).

Schema 3 / compiler semantics 3 are RELEASED semantic authorities. A change
that leaves old documents hashing the same is still a change if it permits
design science that old schema-3 readers refused: the schema would then mean
two different things depending on which binary reads it.

`tests/fixtures/v3_identity_golden.json` was generated by running
`scripts/gen_v3_identity_golden.py` against the frozen commit
`325df2d5b8bc1c007ce1822be4a5ffd4f11f1002`. It records, for every pinned v3
example and every representative v3 request shape:

  design_hash        the v3 identity
  canonical_sha256   sha256 of canonical_dict() JSON
  to_dict_sha256     sha256 of to_dict() JSON
  compiled           the v3 compiler's own verdict

If any of these move, v3's meaning moved. Golden values are NOT to be
regenerated to make a test pass — a mismatch means the code is wrong.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

DSE = Path(__file__).parent.parent
REPO = DSE.parents[2]
sys.path.insert(0, str(DSE))

sys.path.insert(0, str(DSE / "scripts"))
from gen_v3_identity_golden import build  # noqa: E402

from veritx_dse.model.compile_model import (  # noqa: E402
    CompileRequestV3, CompileRequestV3SchemaError,
)

GOLDEN = json.loads(
    (DSE / "tests/fixtures/v3_identity_golden.json").read_text())


def test_v3_golden_covers_examples_and_representative_shapes():
    keys = set(GOLDEN["entries"])
    assert any(k.startswith("examples/") for k in keys)
    assert any(k.startswith("representative/") for k in keys)
    assert len(keys) >= 10, sorted(keys)


def test_v3_identity_is_byte_for_byte_unchanged():
    """The whole point: v3 means exactly what it meant at the freeze."""
    now = build()
    assert set(now["entries"]) == set(GOLDEN["entries"])
    drift = []
    for key, want in GOLDEN["entries"].items():
        got = now["entries"][key]
        for field in ("design_hash", "canonical_sha256", "to_dict_sha256"):
            if got[field] != want[field]:
                drift.append(f"{key}.{field}: {want[field]} -> {got[field]}")
        if got["compiled"] != want["compiled"]:
            drift.append(f"{key}.compiled: {want['compiled']} -> "
                         f"{got['compiled']}")
    assert not drift, "SCHEMA 3 SEMANTICS MOVED:\n  " + "\n  ".join(drift)


def test_v3_compiler_verdicts_unchanged():
    """Mesh and explicit-custom compilation must be unchanged too — a hash is
    not the only externally visible v3 contract."""
    for key, entry in GOLDEN["entries"].items():
        want = entry["compiled"]
        got = build()["entries"][key]["compiled"]
        assert got["status"] == want["status"], key
        assert got.get("family") == want.get("family"), key
        assert got.get("router_count") == want.get("router_count"), key
        assert got.get("topology_hash") == want.get("topology_hash"), key


# ══ v3 must REJECT the v4 vocabulary ══════════════════════════════════

def _v3_doc():
    doc = json.loads(
        (REPO / "tracks/t3-topology/examples/dense_1b_16tiles-v3.json"
         ).read_text())
    doc.pop("design_hash", None)
    doc.pop("guardrail_hash", None)
    return doc


def test_v3_rejects_topology_intent_as_an_unknown_field():
    doc = _v3_doc()
    doc["topology_intent"] = {"kind": "mesh", "side_length": 4}
    with pytest.raises(CompileRequestV3SchemaError,
                       match="topology_intent"):
        CompileRequestV3.from_dict(doc)


def test_v3_rejects_noc_controls_as_an_unknown_field():
    doc = _v3_doc()
    doc["noc_controls"] = {"arbitration": "round_robin"}
    with pytest.raises(CompileRequestV3SchemaError, match="noc_controls"):
        CompileRequestV3.from_dict(doc)


def test_v3_rejects_a_v4_document():
    doc = _v3_doc()
    doc["schema_version"] = 4
    with pytest.raises(CompileRequestV3SchemaError):
        CompileRequestV3.from_dict(doc)


def test_v3_exactly_one_topology_source_law_is_unchanged():
    """Named family XOR explicit graph — and no third source."""
    from veritx_dse.model import topology_ir as tir
    doc = _v3_doc()
    doc["noc_config"] = dict(doc["noc_config"])
    doc["noc_config"]["topology_family"] = "mesh"
    doc["explicit_topology"] = tir.from_dict({
        "name": "g", "kind": "custom", "nodes": 4,
        "links": [[0, 1], [1, 2], [2, 3]],
        "link_attrs": {"bandwidth_GBs": 50.0, "latency_ns": 500.0},
    }).to_dict()
    with pytest.raises(CompileRequestV3SchemaError):
        CompileRequestV3.from_dict(doc)


def test_v3_has_no_topology_intent_attribute():
    """The field must not exist on the type at all — not merely be rejected."""
    import dataclasses
    names = {f.name for f in dataclasses.fields(CompileRequestV3)}
    assert "topology_intent" not in names
    assert not hasattr(CompileRequestV3, "topology_intent")


def test_v3_top_level_key_set_is_frozen():
    from veritx_dse.model.compile_model import _TOP_V3_KEYS
    assert "topology_intent" not in _TOP_V3_KEYS
    assert "noc_controls" not in _TOP_V3_KEYS
