"""Study-integrity regression pins — post-freeze adversarial-review fixes.

Wave-A authority contract:

  * serving: the CLUSTER is the fabric intent. The slice resolves the
    expected cluster-derived fabric BEFORE Run.create (it rides the
    experiment hash), records the executed fabric, and fails the run
    closed unless expected == executed. A serving spec may not carry a
    standalone network preset at all.
  * standalone: a named preset OWNS its routing; ``routing=None`` means
    "no opinion" and resolves to the preset's native routing; anything
    else is rejected before a run directory exists.
  * compiler: failure/unmeasurable/pruned is never NO_FEASIBLE_DESIGN.
  * comparison: a mandatory dimension that is None on BOTH sides is
    unresolved, not equal — certification requires recorded evidence.

Each test names the defect it pins. These are fast, simulator-free pins
at the seams; live end-to-end behavior stays with the slice tests.
"""
import json
import os
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

from veritx_dse.core.errors import ServingResultError
from veritx_dse.core.serving import (
    check_fabric_matches_intent,
    executed_fabric_identity,
    render_expected_booksim_config,
    resolve_serving_fabric_identity,
)
from veritx_dse.core.paths import serving_fixture


# ── helpers ─────────────────────────────────────────────────────────────

def _cfg(tmp_path: Path, body: str) -> Path:
    d = tmp_path / "inputs" / "booksim"
    d.mkdir(parents=True, exist_ok=True)
    p = d / "config.cfg"
    p.write_text(textwrap.dedent(body))
    return p


def _anynet(tmp_path: Path, nodes: int = 3) -> Path:
    d = tmp_path / "inputs" / "booksim"
    d.mkdir(parents=True, exist_ok=True)
    (d / "topo.anynet").write_text(
        "".join(f"router {i} node {i}\n" for i in range(nodes)))
    (d / "config.cfg").write_text(
        f"topology = anynet;\nnetwork_file = {d / 'topo.anynet'};\n"
        "routing_function = min;\nnum_vcs = 16;\npacket_size = 64;\n")
    return d / "config.cfg"


MESH_2x2 = """\
    // BookSim config for ASTRA-sim backend
    // Generated by LLMServingSim
    topology = mesh;
    k = 2;
    n = 2;
    routing_function = dor;
    num_vcs = 16;
    vc_buf_size = 512;
    packet_size = 64;
    injection_rate = 0.0;
    """


# ── executed-fabric identity (P0 #1/#9: execution-side truth) ──────────

class TestExecutedFabricIdentity:
    def test_parses_generated_mesh_config(self, tmp_path):
        p = _cfg(tmp_path, MESH_2x2)
        ident = executed_fabric_identity(p)
        assert ident["topology"] == "mesh"
        assert ident["size"] == {"k": "2", "n": "2"}
        assert ident["routing"] == "dor"
        assert ident["num_vcs"] == "16"
        assert ident["packet_size"] == "64"
        assert ident["config_sha256"].startswith("sha256:")

    def test_missing_config_is_a_hard_error(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            executed_fabric_identity(tmp_path / "nope" / "config.cfg")

    def test_anynet_node_count_and_hash(self, tmp_path):
        p = _anynet(tmp_path, nodes=3)
        ident = executed_fabric_identity(p)
        assert ident["size"]["anynet_nodes"] == 3
        assert ident["anynet_sha256"].startswith("sha256:")

    def test_network_yml_hash_recorded_when_present(self, tmp_path):
        _cfg(tmp_path, MESH_2x2)
        yml = tmp_path / "inputs" / "network" / "network.yml"
        yml.parent.mkdir(parents=True)
        yml.write_text("topology: [FullyConnected]\nnpus_count: [2, 2]\n")
        ident = executed_fabric_identity(
            tmp_path / "inputs" / "booksim" / "config.cfg")
        assert ident["network_yml_sha256"].startswith("sha256:")

    def test_identity_is_deterministic(self, tmp_path):
        p = _cfg(tmp_path, MESH_2x2)
        assert (executed_fabric_identity(p)["config_sha256"]
                == executed_fabric_identity(p)["config_sha256"])


# ── cluster→fabric resolution (P0 #1/#2: the cluster is the authority) ───

class TestServingFabricResolution:
    def test_single_tp2_ep2_lowers_to_mesh_dor(self):
        expected = resolve_serving_fabric_identity(
            serving_fixture("cluster", "single_tp2_ep2"))
        assert expected["source"] == "serving_cluster"
        assert expected == {
            "source": "serving_cluster", "topology": "mesh",
            "routing": "dor", "dimensions": [2], "npu_count": 2,
            "cluster_id": "single_node_moe_single_instance",
            "k": 2, "n": 1, "num_vcs": 16, "vc_buf_size": 512,
            "packet_size": 64, "flit_size": 64}

    def test_multi_dp_tp_lowers_to_square_mesh(self):
        expected = resolve_serving_fabric_identity(
            serving_fixture("cluster", "multi_dp_tp"))
        assert expected["topology"] == "mesh"
        assert expected["routing"] == "dor"
        assert expected["dimensions"] == [2, 2]
        assert expected["npu_count"] == 4
        assert (expected["k"], expected["n"]) == (2, 2)

    def test_resolution_uses_child_arithmetic_not_a_replica(self):
        import inspect
        src = inspect.getsource(resolve_serving_fabric_identity)
        assert "_compute_network_dims" in src
        assert "_resolve_parallelism" in src

    def test_malformed_cluster_fails_closed(self, tmp_path):
        bad = tmp_path / "cluster.json"
        bad.write_text(json.dumps({"nodes": []}))
        with pytest.raises(ServingResultError) as exc:
            resolve_serving_fabric_identity(bad)
        assert exc.value.reason == "CLUSTER_FABRIC_UNRESOLVABLE"

    def test_render_matches_child_template_bytes(self):
        expected = resolve_serving_fabric_identity(
            serving_fixture("cluster", "single_tp2_ep2"))
        text = render_expected_booksim_config(expected)
        assert "topology = mesh;" in text
        assert "k = 2;" in text and "n = 1;" in text
        assert "routing_function = dor;" in text
        assert "injection_rate = 0.0;" in text  # no self-injection


# ── expected == executed (P0 #1: the join is proven, not assumed) ──────

class TestFabricAuthority:
    def test_matching_mesh_accepts(self):
        expected = resolve_serving_fabric_identity(
            serving_fixture("cluster", "single_tp2_ep2"))
        executed = executed_fabric_identity(_k2n1_cfg())
        check_fabric_matches_intent(executed, expected_fabric=expected)

    def test_dimension_contradiction_refused(self):
        """The reviewer's negative: expected dims [2], executed [4]."""
        expected = resolve_serving_fabric_identity(
            serving_fixture("cluster", "single_tp2_ep2"))
        executed = executed_fabric_identity(_k2n1_cfg(k=4))
        with pytest.raises(ServingResultError) as exc:
            check_fabric_matches_intent(executed, expected_fabric=expected)
        assert exc.value.reason == "FABRIC_INTENT_MISMATCH"

    def test_topology_backend_contradiction_refused(self, tmp_path):
        expected = resolve_serving_fabric_identity(
            serving_fixture("cluster", "single_tp2_ep2"))
        executed = executed_fabric_identity(_anynet(tmp_path, nodes=2))
        with pytest.raises(ServingResultError) as exc:
            check_fabric_matches_intent(executed, expected_fabric=expected)
        assert exc.value.reason == "FABRIC_INTENT_MISMATCH"

    def test_anynet_node_count_must_match_cluster(self, tmp_path):
        """Anynet expected vs a 8-node executed clique: the parsed network
        file IS the fabric — node count must equal cluster parallelism."""
        expected = {"source": "serving_cluster", "topology": "anynet",
                    "routing": "min", "dimensions": [8], "npu_count": 8,
                    "num_vcs": 16, "vc_buf_size": 512, "packet_size": 64}
        executed = executed_fabric_identity(_anynet(tmp_path, nodes=8))
        check_fabric_matches_intent(executed, expected_fabric=expected)
        expected4 = {**expected, "npu_count": 4}
        with pytest.raises(ServingResultError) as exc:
            check_fabric_matches_intent(executed, expected_fabric=expected4)
        assert "8 nodes" in str(exc.value)

    def test_routing_contradiction_refused(self):
        expected = resolve_serving_fabric_identity(
            serving_fixture("cluster", "single_tp2_ep2"))
        ident = executed_fabric_identity(_k2n1_cfg())
        forged = {**ident, "routing": "min"}
        with pytest.raises(ServingResultError) as exc:
            check_fabric_matches_intent(forged, expected_fabric=expected)
        assert exc.value.reason == "FABRIC_INTENT_MISMATCH"

    def test_vc_or_packetization_drift_refused(self):
        expected = resolve_serving_fabric_identity(
            serving_fixture("cluster", "single_tp2_ep2"))
        ident = executed_fabric_identity(_k2n1_cfg())
        with pytest.raises(ServingResultError):
            check_fabric_matches_intent(
                {**ident, "num_vcs": "8"}, expected_fabric=expected)
        # Absent (None) keys are not contradictions — other keys decide.
        check_fabric_matches_intent(
            {**ident, "num_vcs": None}, expected_fabric=expected)


def _k2n1_cfg(*, k: int = 2) -> Path:
    """One-shot tmp mesh config in the child's exact template form."""
    import tempfile
    root = Path(tempfile.mkdtemp(prefix="fabric-"))
    body = MESH_2x2.replace("k = 2;", f"k = {k};").replace("n = 2;", "n = 1;")
    return _cfg(root, body)


# ── compiler verdict honesty (P0 #3/#6: failure ≠ infeasible) ──────────

class TestCompilerVerdictHonesty:
    def _compile(self, candidates, evaluate):
        from veritx_dse.synthesis.compiler import CompilerRequest, compile_fabric
        req = CompilerRequest(
            requirements=[{"qos_class": "latency_critical",
                           "latency_ceiling_cycles": 100.0, "binding": True}],
            candidates=candidates)
        return compile_fabric(req, evaluate)

    def test_all_evaluations_fail_is_evaluation_failed(self):
        """Pin H: every evaluator crash ⇒ EVALUATION_FAILED, never
        NO_FEASIBLE_DESIGN."""
        def boom(cand):
            raise RuntimeError("booksim timeout")
        out = self._compile([{"name": "a"}, {"name": "b"}], boom)
        assert out["verdict"] == "EVALUATION_FAILED"
        assert out["failure_reasons"]["evaluation_failed"] == 2
        assert out["pareto"] is None
        assert out["relaxation_information"] is None

    def test_violations_plus_failures_is_evaluation_failed(self):
        """Pin I: 4 violations + 6 failures ⇒ EVALUATION_FAILED (the
        evidence problem dominates the refusal)."""
        def mixed(cand):
            if int(cand["name"]) >= 4:
                raise RuntimeError("sim died")
            return {"name": cand["name"], "topology": "anynet",
                    "backend": "anynet", "nodes": 16, "edges": 32,
                    "latency": 500.0, "status": "ok", "error": None,
                    "seed": 0, "provenance": "stub", "extra": {}}
        out = self._compile([{"name": str(i)} for i in range(10)], mixed)
        assert out["verdict"] == "EVALUATION_FAILED"

    def test_all_unmeasurable_is_constraint_unmeasurable(self):
        """10 unmeasurable ⇒ CONSTRAINT_UNMEASURABLE. Unmeasurable means
        the required metric has NO measured producer (here: a binding
        bandwidth_floor the stack cannot measure) — distinct from an
        evaluation crash (latency=None ⇒ EVALUATION_FAILED)."""
        from veritx_dse.synthesis.compiler import CompilerRequest, compile_fabric

        def ok_latency(cand):
            return {"name": cand["name"], "topology": "anynet",
                    "backend": "anynet", "nodes": 16, "edges": 32,
                    "latency": 50.0, "status": "ok", "error": None,
                    "seed": 0, "provenance": "stub", "extra": {}}
        req = CompilerRequest(
            requirements=[{"qos_class": "latency_critical",
                           "bandwidth_floor_gbps": 10.0,
                           "binding": True}],
            candidates=[{"name": str(i)} for i in range(10)])
        out = compile_fabric(req, ok_latency)
        assert out["verdict"] == "CONSTRAINT_UNMEASURABLE"
        assert out["relaxation_information"] is None
        assert out["pareto"] is None

    def test_all_measured_violations_is_no_feasible_design(self):
        """Pin J: 10 successfully measured violations — the ONLY legal
        NO_FEASIBLE_DESIGN, and the only verdict carrying relaxation."""
        def violator(cand):
            return {"name": cand["name"], "topology": "anynet",
                    "backend": "anynet", "nodes": 16, "edges": 32,
                    "latency": 500.0, "status": "ok", "error": None,
                    "seed": 0, "provenance": "stub", "extra": {}}
        out = self._compile([{"name": str(i)} for i in range(10)], violator)
        assert out["verdict"] == "NO_FEASIBLE_DESIGN"
        assert out["violated_constraints"]
        assert out["relaxation_information"]  # valid: fully measured

    def test_violations_plus_pruned_is_search_incomplete(self):
        """4 violations + 6 pruned ⇒ SEARCH_INCOMPLETE (space not
        exhausted, and the evaluated subset alone must not refuse)."""
        from veritx_dse.synthesis import compiler as C
        verdict = C._verdict_from_counts(
            records=[{"status": C.ST_CONSTRAINT_VIOLATION}] * 4
                    + [{"status": C.ST_PRUNED}] * 6,
            n_feasible=0, n_violated=4, n_failed=0,
            n_unmeasurable=0, n_pruned=6)
        assert verdict == C.VERDICT_SEARCH_INCOMPLETE
        # And the pure decision order, pinned exactly:
        assert C._verdict_from_counts(
            records=[{"status": C.ST_CONSTRAINT_VIOLATION}] * 10,
            n_feasible=0, n_violated=10, n_failed=0,
            n_unmeasurable=0, n_pruned=0) == C.VERDICT_NO_FEASIBLE_DESIGN
        assert C._verdict_from_counts(
            records=[], n_feasible=0, n_violated=0, n_failed=0,
            n_unmeasurable=0, n_pruned=0) == C.VERDICT_SEARCH_INCOMPLETE

    def test_one_feasible_among_failures_is_feasible(self):
        """1 feasible + 9 failures ⇒ FEASIBLE (a real design exists)."""
        def one_ok(cand):
            if cand["name"] == "good":
                return {"name": "good", "topology": "anynet",
                        "backend": "anynet", "nodes": 16, "edges": 32,
                        "latency": 50.0, "status": "ok", "error": None,
                        "seed": 0, "provenance": "stub", "extra": {}}
            raise RuntimeError("sim died")
        out = self._compile([{"name": str(i)} for i in range(9)]
                            + [{"name": "good"}], one_ok)
        assert out["verdict"] == "FEASIBLE"
        assert out["pareto"] is not None


# ── comparison certification completeness (P0 #4/#7) ───────────────────

def _write_run(tmp_path: Path, *, with_fabric: bool) -> Path:
    run = tmp_path / "run1"
    (run / "artifacts").mkdir(parents=True)
    (run / "workload").mkdir(parents=True)  # certified workload identity
    (run / "workload" / "index.json").write_text(json.dumps({
        "schema_version": 1,
        "artifacts": [{"trace": "trace/r0.txt",
                       "artifact_hash": "sha256:" + "c" * 64}]}))
    (run / "spec.resolved.json").write_text(json.dumps({
        "workload": {"id": "w", "trace": "archive/inputs/traces/x.trace"},
        "system": {"nodes": 8, "tp_size": 2, "instances_per_node": 1},
        "simulation": {"mode": "serving", "timeout_s": 60},
        "replication": {"mode": "deterministic", "seeds": [42]},
        "serving": {"cluster": "single_tp2_ep2", "dataset": "example",
                    "num_reqs": 1, "network_backend": "booksim",
                    "cycle_accurate": True,
                    "request_routing_policy": "LOAD"},
    }))
    results = [{
        "task_id": "serve",
        "provenance": {"engine": "llmservingsim",
                       "network_backend": "booksim",
                       "network_mode": "REAL_SIMULATION",
                       "semantic_losses": [],
                       "fidelity": "SYSTEM_SERVING_SIMULATION"},
        "metric_schema": 1,
        "metrics": {"TTFT": {"value": 1.0, "unit": "ns",
                             "producer": "llmservingsim",
                             "fidelity": "SYSTEM_SERVING_SIMULATION",
                             "scope": "per_request"}},
    }]
    if with_fabric:
        results[0]["executed_fabric"] = {
            "topology": "mesh", "size": {"k": "2", "n": "1"},
            "routing": "dor", "num_vcs": "16", "vc_buf_size": "512",
            "packet_size": "64",
            "config_sha256": "sha256:" + "a" * 64,
            "network_yml_sha256": "sha256:" + "b" * 64,
        }
    (run / "manifest.json").write_text(json.dumps(
        {"schema_version": 1, "run_id": "run1", "status": "SUCCEEDED",
         "results": results}))
    return run


class TestComparisonCertification:
    def test_no_executed_fabric_is_insufficient_provenance(self, tmp_path):
        """Pin K: absence of evidence is not equality. vc/packetization
        unresolved ⇒ certified=False + INSUFFICIENT_PROVENANCE."""
        from veritx_dse.core.comparison import fingerprint_from_run
        fp = fingerprint_from_run(_write_run(tmp_path, with_fabric=False))
        assert fp["vc_count"] is None
        assert fp["packetization"] is None
        assert fp["certified"] is False
        assert fp["certification_status"] == "INSUFFICIENT_PROVENANCE"
        assert "vc_count" in fp["unresolved_dimensions"]
        assert "packetization" in fp["unresolved_dimensions"]

    def test_executed_fabric_resolves_identity_and_certifies(self, tmp_path):
        from veritx_dse.core.comparison import fingerprint_from_run
        fp = fingerprint_from_run(_write_run(tmp_path, with_fabric=True))
        assert fp["vc_count"] == 16
        assert fp["packetization"] == 64
        assert fp["topology"] == "mesh"      # executed evidence, serving
        assert fp["routing"] == "dor"
        assert fp["certified"] is True
        assert fp["certification_status"] == "RESOLVED"
        assert fp["executed_topology"] == "mesh"
        assert fp["executed_config_sha256"].startswith("sha256:")

    def test_two_nones_are_not_equality(self, tmp_path):
        """Two candidates that BOTH fail to record vc_count must not pass
        certification because 'both are None' — shared ignorance is not
        equality."""
        from veritx_dse.core.comparison import (
            evaluate_comparability, fingerprint_from_run)
        run_a = _write_run(tmp_path / "a", with_fabric=False)
        run_b = _write_run(tmp_path / "b", with_fabric=False)
        (tmp_path / "a").mkdir(parents=True, exist_ok=True)
        fp_a = fingerprint_from_run(run_a)
        fp_b = fingerprint_from_run(run_b)
        assert not fp_a["certified"] and not fp_b["certified"]
        verdict = evaluate_comparability(
            [fp_a, fp_b],
            {"kind": "DESIGN_COMPARISON", "objectives": ["latency"],
             "experimental_variables": [], "controlled_dimensions": {}})
        assert verdict.certified is False

    def test_legacy_rows_stay_uncertified(self):
        from veritx_dse.core.comparison import fingerprint_from_legacy_row
        fp = fingerprint_from_legacy_row({
            "topology": "mesh_4x4", "nodes": 16, "seed": 0,
            "latency": 100.0})
        assert fp["certified"] is False
        assert "vc_count" in fp["unresolved_dimensions"]


# ── rank-assignment-preserving workload identity (P0 #11) ──────────────

class TestWorkloadIdentityRankAssignment:
    def _index(self, pairs):
        return {"artifacts": [
            {"trace": t, "artifact_hash": h} for t, h in pairs]}

    def test_identity_preserves_rank_assignment(self):
        """Pin G: rank0=A,rank1=B ≠ rank0=B,rank1=A despite an identical
        artifact multiset — the old sorted-hash-set digest was blind to
        rank assignment."""
        from veritx_dse.workload.serve import workload_identity
        ab = self._index([("trace/r0.txt", "sha256:aaa"),
                          ("trace/r1.txt", "sha256:bbb")])
        ba = self._index([("trace/r0.txt", "sha256:bbb"),
                          ("trace/r1.txt", "sha256:aaa")])
        assert workload_identity(ab) != workload_identity(ba)

    def test_same_assignment_same_identity(self):
        from veritx_dse.workload.serve import workload_identity
        i1 = self._index([("trace/r0.txt", "sha256:aaa"),
                          ("trace/r1.txt", "sha256:bbb")])
        i2 = self._index([("trace/r0.txt", "sha256:aaa"),
                          ("trace/r1.txt", "sha256:bbb")])
        assert workload_identity(i1) == workload_identity(i2)

    def test_identity_canonicalizes_by_rank_key(self):
        """The digest canonicalizes by trace path (rank key), never by
        sorting artifact hashes — assignment survives hashing."""
        from veritx_dse.workload.serve import workload_identity
        listed = self._index([("trace/r1.txt", "sha256:bbb"),
                              ("trace/r0.txt", "sha256:aaa")])
        ordered = self._index([("trace/r0.txt", "sha256:aaa"),
                               ("trace/r1.txt", "sha256:bbb")])
        assert workload_identity(listed) == workload_identity(ordered)

    def test_single_artifact_identity_unchanged(self):
        from veritx_dse.workload.serve import workload_identity
        assert workload_identity(self._index(
            [("trace/r0.txt", "sha256:aaa")])) == "sha256:aaa"

    def test_empty_index_fail_closed(self):
        from veritx_dse.workload.canonical import WorkloadError
        from veritx_dse.workload.serve import workload_identity
        with pytest.raises(WorkloadError):
            workload_identity({"artifacts": []})


# ── preset routing immutability (P0 #10: no silent preset mutation) ────

class TestPresetRoutingImmutability:
    def _spec(self, routing):
        d = {"name": "t", "workload": {"id": "w", "trace": "x"},
             "system": {"nodes": 64},
             "network": {"topology": "mesh_8x8"},
             "simulation": {"mode": "latency", "timeout_s": 5}}
        if routing is not None:
            d["network"]["routing"] = routing
        return d

    def test_omitted_routing_resolves_to_preset_native(self):
        """Pin A: mesh_8x8 + omitted routing → min_adapt."""
        from veritx_dse.core.spec import parse, resolve
        r = resolve(parse(self._spec(None)))
        assert r["network"]["routing"] == "min_adapt"

    def test_explicit_native_is_hash_identical_to_omitted(self):
        """Pin B: omitted and explicit-native are the SAME intent."""
        from veritx_dse.core.spec import experiment_hash, parse, resolve
        h_omitted = experiment_hash(resolve(parse(self._spec(None))))
        h_native = experiment_hash(resolve(parse(self._spec("min_adapt"))))
        assert h_omitted == h_native

    def test_foreign_routing_rejected_before_run_creation(self, tmp_path):
        """Pin C: mesh_8x8 + dim_order → SpecError, nothing created."""
        from veritx_dse.core.spec import SpecError
        from veritx_dse.core.experiment import run_experiment
        with pytest.raises(SpecError, match="owns routing"):
            run_experiment(self._spec("dim_order"), repo=tmp_path)
        assert not (tmp_path / "runs").exists()

    def test_torus_native_is_dim_order(self):
        from veritx_dse.core.spec import parse, resolve
        d = self._spec(None)
        d["network"] = {"topology": "torus_8x8"}
        assert resolve(parse(d))["network"]["routing"] == "dim_order"

    def test_presets_declare_their_routing(self):
        from veritx_dse.model.presets import _TOPO_BY_NAME
        assert _TOPO_BY_NAME["mesh_8x8"].routing == "min_adapt"
        assert _TOPO_BY_NAME["torus_8x8"].routing == "dim_order"

    def test_no_replace_mutation_in_run_experiment(self):
        """The old ``topo = replace(topo, routing=...)`` shape is gone —
        presets are consumed, never mutated."""
        src = Path(__file__).parents[1].joinpath(
            "veritx_dse", "core", "experiment.py").read_text()
        assert "replace(topo, routing" not in src


# ── serving specs may not carry standalone network intent (P0 #2) ──────

class TestServingSpecNetworkRejected:
    def _spec(self):
        return {"name": "t", "workload": {"id": "w", "trace": "x"},
                "system": {"nodes": 1},
                "network": {"topology": "mesh_8x8"},
                "simulation": {"mode": "serving", "timeout_s": 5},
                "serving": {"cluster": "single_tp2_ep2",
                            "dataset": "example", "num_reqs": 1}}

    def test_network_block_on_serving_spec_rejected(self):
        from veritx_dse.core.spec import SpecError, parse, resolve
        with pytest.raises(SpecError, match="cluster-derived"):
            resolve(parse(self._spec()))

    def test_serving_without_network_is_accepted(self):
        from veritx_dse.core.spec import parse, resolve
        d = self._spec()
        del d["network"]
        r = resolve(parse(d))
        assert "network" not in r or r["network"] is None
        assert r["serving"]["cluster"] == "single_tp2_ep2"


# ── T3 failure propagation (P0 #9: a failed child cannot read as done) ──

class TestT3FailurePropagation:
    """Functional shell test: source the real t3 in a subshell, force the
    guided-flow child to exit 7, and prove failure propagates."""

    T3 = Path(__file__).parents[2] / "t3"

    def _bash(self, script: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["bash", "-c", script], capture_output=True, text=True,
            timeout=30, env={**os.environ, "TERM": "dumb"})

    def test_ui_open_returns_child_rc(self):
        """Pin L (part 1): ``_ui_open`` ends with ``return "$_rc"`` — the
        regression that made a failed step invisible to guided flows
        (they marched on and announced success). The full functional call
        lives behind t3's container dispatch, so the contract is pinned
        textually plus the chain semantics functionally below."""
        text = self.T3.read_text()
        body = text.split("_ui_open() {", 1)[1].split("\n_ui_", 1)[0]
        assert 'return "$_rc"' in body
        # And the failure is PRINTED (observable to the human too).
        assert 'failed (exit $_rc)' in body

    def test_start_here_chain_short_circuits_on_failure(self):
        """Pin L (part 2): the guided-flow shape ``step || return`` must
        never run step 2 after step 1 fails, and the flow exits nonzero."""
        r = self._bash(
            'step() { return 7; }; '
            'step || { echo "step1 failed"; exit 7; }; '
            'echo UNREACHABLE')
        assert r.returncode == 7
        assert "UNREACHABLE" not in r.stdout


# ── serving child: no architecture invention (P0 #8, source-text pin) ──

class TestServingChildNoInvention:
    def test_no_infer_dims_fallback_in_child(self):
        src = Path(__file__).parents[3].joinpath(
            "third_party", "llmservingsim", "serving", "__main__.py")
        if not src.is_file():
            pytest.skip("LLMServingSim not vendored")
        text = src.read_text()
        assert "_infer_dims" not in text, (
            "the silent dims-invention fallback must stay dead")
        assert "refusing to invent a network architecture" in text

    def test_child_emits_fabric_ledger_line(self):
        src = Path(__file__).parents[3].joinpath(
            "third_party", "llmservingsim", "serving", "__main__.py")
        if not src.is_file():
            pytest.skip("LLMServingSim not vendored")
        assert "[LEDGER][FABRIC]" in src.read_text(), (
            "the child must report the fabric BookSim will actually parse")


# ── slice wiring: the fabric check runs inside the run (P0 #1) ─────────

class TestSliceFabricGateWiring:
    def test_slice_records_and_enforces_fabric(self, tmp_path, monkeypatch):
        """End-to-end through run_serving_experiment with a faked child:
        the run must carry executed_fabric evidence, and a fabricated
        contradiction must fail the run (dims [2] vs executed [4])."""
        import csv as _csv
        import veritx_dse.core.process as proc
        from veritx_dse.core.experiment_serving import run_serving_experiment
        from veritx_dse.core.serving import (
            render_expected_booksim_config,
            resolve_serving_fabric_identity,
        )

        expected = resolve_serving_fabric_identity(
            serving_fixture("cluster", "single_tp2_ep2"))
        forged = {**expected, "k": 4, "n": 1}
        err = ("[LEDGER][TOPO] npus=1 dims=1\n"
               "[LEDGER][COLL_COMPLETE] x\n"
               "[LEDGER][STATE] y retired_flits=64 tail_deliveries=2\n")

        def fake(cmd, **kw):
            root = Path(cmd[cmd.index("--inputs-root") + 1])
            bdir = root / "booksim"
            bdir.mkdir(parents=True, exist_ok=True)
            # The child executed a DIFFERENT mesh than the cluster owns.
            (bdir / "config.cfg").write_text(
                render_expected_booksim_config(forged))
            csvp = [a for a in cmd if a.endswith(".csv")][0]
            with open(csvp, "w", newline="") as f:
                w = _csv.writer(f)
                w.writerow(["instance id", "request id", "arrival",
                            "end_time", "latency", "TTFT", "TPOT", "ITL"])
                w.writerow(["0", "0", "100", "1100", "1000", "700",
                            "100", "[100]"])
            tdir = root / "trace" / "fake_hw" / "fake_model"
            tdir.mkdir(parents=True, exist_ok=True)
            (tdir / "instance0_batch1.txt").write_text(
                "SYNTHETIC\\t\\tmodel_parallel_NPU_group: 1\\n"
                "1\\n"
                "embedding_0 1000 LOCAL 1024 LOCAL 2048 LOCAL 512"
                " NONE 0 1\\n")
            r = type("R", (), {})()
            r.returncode, r.stdout, r.stderr = 0, "out", err
            r.wall_time_s = 1.0
            return r

        monkeypatch.setattr(proc, "supervised_run", fake)
        monkeypatch.setattr("veritx_dse.core.runs.VERITX_RUNS_DIR",
                            tmp_path / "runs")
        spec = {
            "name": "fabric-gate",
            "workload": {"id": "w", "trace": "archive/inputs/traces/x.trace"},
            "system": {"nodes": 1},
            # NO network block: the cluster owns serving fabric intent.
            "simulation": {"mode": "serving", "timeout_s": 60},
            "serving": {"cluster": "single_tp2_ep2", "dataset": "example",
                        "num_reqs": 1},
        }
        run = run_serving_experiment(spec, repo=tmp_path)
        assert run.state == "FAILED"
        results = json.loads(
            (run.root / "manifest.json").read_text())["results"]
        assert results[0]["error"] == "FABRIC_INTENT_MISMATCH"
        assert results[0]["expected_fabric"]["k"] == 2
        assert results[0]["executed_fabric"]["size"] == {"k": "4", "n": "1"}


# ── Wave B: content-addressed fabric/mapping identity (audit #1/#26/#36) ─

class TestFabricArtifactIdentity:
    """Mutation property: any result-affecting fabric change forks the
    artifact hash; identical fabrics hash identically across authorities."""

    def test_param_mutation_forks_hash(self):
        from veritx_dse.core.fabric import fabric_from_preset
        from veritx_dse.model.presets import lookup_topo
        from veritx_dse.simulation.booksim import resolve_fabric_params
        topo = lookup_topo("mesh_8x8")
        base = resolve_fabric_params(topo)
        a1 = fabric_from_preset(topo, sim_params=base, node_count=64)
        bumped = dict(base, num_vcs=base["num_vcs"] + 1)
        a2 = fabric_from_preset(topo, sim_params=bumped, node_count=64)
        assert a1.artifact_hash != a2.artifact_hash, \
            "a VC change that alters execution must fork fabric identity"

    def test_same_preset_same_hash(self):
        from veritx_dse.core.fabric import fabric_from_preset
        from veritx_dse.model.presets import lookup_topo
        from veritx_dse.simulation.booksim import resolve_fabric_params
        topo = lookup_topo("mesh_8x8")
        params = resolve_fabric_params(topo)
        a1 = fabric_from_preset(topo, sim_params=params, node_count=64)
        a2 = fabric_from_preset(topo, sim_params=params, node_count=64)
        assert a1.artifact_hash == a2.artifact_hash

    def test_resolution_binds_artifact_in_intent(self):
        """The resolved spec carries the artifact, so experiment_hash
        (intent identity) forks on fabric changes — audit #26's first
        link in the intent→execution hash chain."""
        from veritx_dse.core.spec import parse, resolve
        d = {"name": "t", "workload": {"id": "w", "trace": "x"},
             "system": {"nodes": 64},
             "network": {"topology": "mesh_8x8"},
             "simulation": {"mode": "latency", "timeout_s": 5},
             "replication": {"mode": "deterministic", "seeds": [42]}}
        r1 = resolve(parse(d))
        assert r1["fabric_artifact"]["topology_id"] == "mesh_8x8"
        assert r1["fabric_artifact"]["routing"] == "min_adapt"
        d2 = json.loads(json.dumps(d))
        d2["network"] = {"topology": "torus_8x8"}
        r2 = resolve(parse(d2))
        assert (r1["fabric_artifact"]["artifact_hash"]
                != r2["fabric_artifact"]["artifact_hash"])

    def test_standalone_fingerprint_binding_certifies(self, tmp_path):
        """A standalone run whose results record the artifact hash it
        executed gets fabric identity resolved — the Wave-B executed-
        evidence path for Slice A (comparison.py artifact_bound)."""
        from veritx_dse.core.spec import parse, resolve
        d = {"name": "t", "workload": {"id": "w", "trace": "x"},
             "system": {"nodes": 64},
             "network": {"topology": "mesh_8x8"},
             "simulation": {"mode": "latency", "timeout_s": 5},
             "replication": {"mode": "deterministic", "seeds": [42]}}
        r = resolve(parse(d))
        fa = r["fabric_artifact"]
        run_dir = tmp_path / "runA"
        (run_dir / "workload").mkdir(parents=True)
        (run_dir / "workload" / "index.json").write_text(json.dumps({
            "schema_version": 1,
            "artifacts": [{"trace": "trace/r0.txt",
                           "artifact_hash": "sha256:" + "c" * 64}]}))
        (run_dir / "spec.resolved.json").write_text(json.dumps(r))
        (run_dir / "manifest.json").write_text(json.dumps({
            "schema_version": 1, "run_id": "runA",
            "status": "SUCCEEDED",
            "results": [{
                "task_id": "eval-seed42",
                "fabric_artifact_hash": fa["artifact_hash"],
                "provenance": {"engine": "booksim",
                               "network_backend": "booksim",
                               "network_mode": "REAL_SIMULATION",
                               "semantic_losses": [],
                               "fidelity": "NETWORK_SIMULATION"},
                "metric_schema": 1,
                "metrics": {"latency": {"value": 1.0, "unit": "cycles",
                                        "producer": "booksim",
                                        "fidelity": "NETWORK_SIMULATION",
                                        "scope": "per_packet"}},
            }]}))
        from veritx_dse.core.comparison import fingerprint_from_run
        fp = fingerprint_from_run(run_dir)
        assert fp["topology"] == "mesh_8x8"
        assert fp["vc_count"] == fa["vc_count"]
        assert fp["packetization"] == fa["packet_size_flits"]
        assert fp["fabric_artifact_hash"] == fa["artifact_hash"]
        assert fp["certified"] is True

    def test_hash_mismatch_does_not_certify(self, tmp_path):
        """A result recording a DIFFERENT artifact hash than the spec
        binds is not a bound execution — no certification."""
        from veritx_dse.core.spec import parse, resolve
        d = {"name": "t", "workload": {"id": "w", "trace": "x"},
             "system": {"nodes": 64},
             "network": {"topology": "mesh_8x8"},
             "simulation": {"mode": "latency", "timeout_s": 5},
             "replication": {"mode": "deterministic", "seeds": [42]}}
        r = resolve(parse(d))
        run_dir = tmp_path / "runB"
        (run_dir / "workload").mkdir(parents=True)
        (run_dir / "workload" / "index.json").write_text(json.dumps({
            "schema_version": 1,
            "artifacts": [{"trace": "trace/r0.txt",
                           "artifact_hash": "sha256:" + "c" * 64}]}))
        (run_dir / "spec.resolved.json").write_text(json.dumps(r))
        (run_dir / "manifest.json").write_text(json.dumps({
            "schema_version": 1, "run_id": "runB",
            "status": "SUCCEEDED",
            "results": [{
                "task_id": "eval-seed42",
                "fabric_artifact_hash": "sha256:" + "d" * 64,
                "metric_schema": 1, "metrics": {}}]}))
        from veritx_dse.core.comparison import fingerprint_from_run
        fp = fingerprint_from_run(run_dir)
        assert fp["certified"] is False


class TestMappingArtifactIdentity:
    """Audit #25: placement is identity. Ordered rank entries, content-
    addressed, canonicalized by rank key."""

    def test_rank_swap_forks_identity(self):
        from veritx_dse.core.fabric import mapping_artifact
        m1 = mapping_artifact(authority="serving_workload", entries=[
            {"rank": 0, "device": "A"}, {"rank": 1, "device": "B"}])
        m2 = mapping_artifact(authority="serving_workload", entries=[
            {"rank": 0, "device": "B"}, {"rank": 1, "device": "A"}])
        assert m1.mapping_hash != m2.mapping_hash

    def test_input_order_is_canonicalized_by_rank(self):
        from veritx_dse.core.fabric import mapping_artifact
        m1 = mapping_artifact(authority="a", entries=[
            {"rank": 0, "device": "A"}, {"rank": 1, "device": "B"}])
        m2 = mapping_artifact(authority="a", entries=[
            {"rank": 1, "device": "B"}, {"rank": 0, "device": "A"}])
        assert m1.mapping_hash == m2.mapping_hash

    def test_gap_and_tamper_refused(self):
        from veritx_dse.core.fabric import MappingArtifact, mapping_artifact
        with pytest.raises(Exception):
            mapping_artifact(authority="a", entries=[
                {"rank": 0, "device": "A"}, {"rank": 2, "device": "C"}])
        m = mapping_artifact(authority="a", entries=[
            {"rank": 0, "device": "A"}, {"rank": 1, "device": "B"}])
        d = m.to_dict()
        d["entries"][0]["device"] = "TAMPERED"
        with pytest.raises(Exception):
            MappingArtifact.from_dict(d)
