"""SEALED PREPARED-INPUT BYTES (PHASE B.2 §10).

PHASE B.1 changed how a design request is EXPRESSED (schema 4, typed topology
intent, normalized generation seam) without touching the BookSim fork or
either sealed profile. "The Python files are unchanged" is not the proof that
matters; this is:

    SAME SEALED SCIENCE  ->  SAME PREPARED BACKEND INPUT BYTES

`tests/fixtures/sealed_prepared_input_golden.json` was generated by running
`scripts/gen_sealed_input_golden.py` AT the frozen pre-B baseline
`325df2d5b8bc1c007ce1822be4a5ffd4f11f1002`, with a fixed seed and canonical
fixtures. It records the exact content digests of every byte the backend
receives: config, trace, `.anynet` topology, and PreparedBookSimInput's own
content identity (which binds the canonical artifact hashes, the profile and
its semantics/lowerer versions).

The golden is NEVER regenerated to make a test pass.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

DSE = Path(__file__).parent.parent
sys.path.insert(0, str(DSE))
sys.path.insert(0, str(DSE / "scripts"))

from gen_sealed_input_golden import build  # noqa: E402

GOLDEN = json.loads(
    (DSE / "tests/fixtures/sealed_prepared_input_golden.json").read_text())

DIGEST_FIELDS = ("config_sha256", "trace_sha256", "topology_bytes_sha256",
                 "prepared_id", "profile_id", "profile_semantics_version",
                 "num_vcs", "endpoint_count", "router_count",
                 "expected_packets", "topology_hash")

def test_golden_covers_both_sealed_profiles():
    profiles = {v["profile_id"] for v in GOLDEN["fixtures"].values()}
    assert profiles == {"CERTIFIED_BOOKSIM_MESH_DOR_XY_V1",
                        "CERTIFIED_BOOKSIM_ANYNET_V1"}

def test_prepared_backend_input_bytes_are_unchanged():
    now = build()
    assert set(now["fixtures"]) == set(GOLDEN["fixtures"])
    drift = []
    for key, want in GOLDEN["fixtures"].items():
        got = now["fixtures"][key]
        for field in DIGEST_FIELDS:
            if got.get(field) != want.get(field):
                drift.append(f"{key}.{field}: {want.get(field)} -> "
                             f"{got.get(field)}")
    assert not drift, (
        "SEALED PREPARED INPUT MOVED — the backend would receive different "
        "bytes for the same science:\n  " + "\n  ".join(drift))

def test_the_sealed_profiles_are_the_ones_actually_selected():
    for key, want in GOLDEN["fixtures"].items():
        assert build()["fixtures"][key]["profile_id"] == want["profile_id"], key

def test_anynet_renders_a_topology_file_and_mesh_does_not():
    """The AnyNet profile renders a `.anynet` link file; the native mesh
    profile does not (its topology is implicit in the mesh config)."""
    a = GOLDEN["fixtures"]["anynet/2x2_explicit"]
    m = GOLDEN["fixtures"]["mesh/mesh_4x4"]
    assert a["topology_bytes_sha256"] is not None
    assert m["topology_bytes_sha256"] is None
