#!/usr/bin/env python3
"""Validate every Studio fixture against the frozen contracts.

Contract versions (C-1): the authoritative OptimizationStudyView is
``contracts/srota/v2/optimization.study.view.schema.json``
(contract_version 2, the only path that carries the three separate
authorities and the three-state constraint verdicts). The other four
views stay on ``contracts/srota/v1/``. The v1-dir v2-named file no
longer exists and is never consulted.

Gates, in order:

  1. SCHEMA: every non-null view validates against its declared contract
     (Draft 2020-12, local files only — no network).
  2. LINKAGE: design_hash consistent across design/compilation/
     evaluation/requirements; optimization.base_design_hash matches;
     requirements.performance_result_id matches evaluation's;
     EVALUATED outcomes carry their required bindings.
  3. ENGINE VOCABULARY / REALIZABILITY (fast path): values must project
     from real engine semantics (enum mirrors + invariants the engine
     enforces), and the v2 study's three-state semantics must be
     coherent (no boolean collapse, pareto_eligible conjunction,
     certified identity present). A self-test proves this gate rejects
     the impossibilities it exists for.
  4. PROVISIONED BACKEND PROOF: only when a qualified BookSim is present
     does the validator regenerate all five fixtures with the engine
     generator (application gateways + Optimize...optimize_certified)
     into a TEMP directory, prove the EVALUATED fixture + its
     RequirementReport + the CERTIFIED_PRODUCT study through the engine
     objects, and compare the regenerated bytes with the committed files
     BYTE-FOR-BYTE. Producer runtime provenance that leaks into contract
     identity fields is REPORTED as an engine defect — never normalized
     away by an allowlist.

Two legitimate environments (C-3):

  * FAST/unprovisioned: parses, compiles, refuses, validates schemas —
    cannot prove backend evaluation or real optimization. Prints exactly
    ``FAST PATH ONLY: backend realizability not proven`` and never a
    generic PASS claiming backend realizability.
  * PROVISIONED: qualified BookSim present — proves the evaluated
    fixture, the RequirementReport and a real OptimizationStudy through
    the engine gateways.

Exit 0 iff every selected gate passes.

Usage:
    python3 scripts/validate_fixtures.py              # fast; engine ON in CI
    python3 scripts/validate_fixtures.py --engine     # force provisioned proof
    python3 scripts/validate_fixtures.py --skip-engine  # offline fast path
"""

from __future__ import annotations

import argparse
import copy
import json
import os
import re
import shutil
import sys
import tempfile
from pathlib import Path

from jsonschema import Draft202012Validator

STUDIO = Path(__file__).resolve().parent.parent  # apps/studio
REPO = STUDIO.parent.parent  # workspace root
SCHEMAS_V1 = REPO / "contracts" / "srota" / "v1"
SCHEMAS_V2 = REPO / "contracts" / "srota" / "v2"
STUDY_SCHEMA_V2 = SCHEMAS_V2 / "optimization.study.view.schema.json"
FIXTURE_DIR = STUDIO / "fixtures"
DSE_DIR = REPO / "tracks" / "t3-topology" / "dse"

FAST_LINE = "FAST PATH ONLY: backend realizability not proven"
PROVEN_LINE = "PROVISIONED: backend realizability PROVEN"

EXPECTED_FIXTURES = {
    "compiled-mesh",
    "invalid-design",
    "backend-unavailable",
    "evaluated-design",
    "optimization-study",
}

ENGINE_TOOL_MODULE = "veritx_dse.tools.generate_studio_fixtures"

# (schema directory, schema file) per view. The study view is v2; the
# other four views remain v1 (C-1).
VIEW_SCHEMAS: dict[str, tuple[Path, str]] = {
    "design": (SCHEMAS_V1, "design.view.schema.json"),
    "compilation": (SCHEMAS_V1, "compilation.view.schema.json"),
    "evaluation": (SCHEMAS_V1, "evaluation.view.schema.json"),
    "requirements": (SCHEMAS_V1, "requirement.report.schema.json"),
    "optimization": (SCHEMAS_V2, "optimization.study.view.schema.json"),
}

# ── engine-mirrored vocabularies (values, never imports) ─────────────────────
# model/compile_model.py::ModelFamily
MODEL_FAMILIES = {
    "dense_transformer",
    "mixture_of_experts",
    "diffusion",
    "cnn",
    "custom",
}
# model/compile_model.py::AgentKind
AGENT_KINDS = {
    "compute_tile",
    "hbm_controller",
    "nic",
    "peripheral",
    "ucie_port",
}
# model/compile_model.py::QoSClass
QOS_CLASSES = {"latency_critical", "bandwidth", "best_effort"}
# model/compile_model.py::TopologyFamily
TOPOLOGY_FAMILIES = {"mesh", "torus", "concentrated_mesh", "gec", "fat_tree"}
# model/compile_model.py::ServingMode
SERVING_MODES = {"prefill_heavy", "decode_heavy", "mixed"}
# model/router_behavior.py::_ARBITRATION_ALIASES
ARBITRATION_ALIASES = {"islip", "round_robin", "round-robin", "rr"}
# optimization/definition.py
OBJECTIVE_DIRECTIONS = {"MIN", "MAX"}
CONSTRAINT_OPS = {"<=", ">="}
# optimization/result.py — never booleans in the authoritative contract
CONSTRAINT_VERDICTS = {"SATISFIED", "VIOLATED", "UNMEASURABLE"}
OBJECTIVE_STATES = {"MEASURED", "UNMEASURABLE"}
COMPILATION_STATUSES = {"COMPILED", "INVALID", "UNSUPPORTED"}
CANDIDATE_EVALUATION_STATUSES = {
    "EVALUATED", "COMPILE_FAILED", "INVALID", "UNSUPPORTED",
    "BACKEND_UNAVAILABLE", "FAILED",
}
CANDIDATE_AUTHORITIES = {"certified-backend", "analytic-fake", None}
RESULT_CLASSES = {"CERTIFIED_PRODUCT", "ANALYTIC_RESEARCH"}
# optimization/metric_registry.py — product-controlled registry
ENGINE_REGISTRY_VERSION = "certified-builtin-v1"

# ── byte-reproducibility regression classification ───────────────────────────
# evidence-v2 (backend/evidence.py) removed the non-semantic runtime fields
# (absolute run directory, measured wall time, host platform text) from the
# scientific evidence document, so none of them can enter
# ``evaluation.evidence.raw_evidence_digest`` or its identity closure any
# more. If a future change re-introduces one, the byte diff lands exactly on
# the paths below: that is an ENGINE DEFECT to report, NOT an equivalence to
# bless (a difference here still fails the gate).
_PROVENANCE_DIFF_PATTERNS: tuple[re.Pattern[str], ...] = tuple(
    re.compile(p) for p in (
        r"^\.evaluation\.evidence\.raw_evidence_digest$",
        r"^\.evaluation\.performance_result_id$",
        r"^\.requirements\.performance_result_id$",
        r"^\.requirements\.entries\[\d+\]\.performance_result_id$",
        r"^\.optimization\.optimization_result_id$",
        r"^\.optimization\.candidates\[\d+\]"
        r"\.evaluation_ids\.performance_result_id$",
        r"^\.optimization\.candidates\[\d+\]"
        r"\.evaluation_ids\.requirement_report_id$",
        r"^\.optimization\.candidates\[\d+\]"
        r"\.product_requirements\.verdicts\[\d+\]\.performance_result_id$",
    )
)


def load_schema(directory: Path, name: str) -> dict:
    return json.loads((directory / name).read_text())


# ── schema validation + linkage ─────────────────────────────────────────────

def check_linkage(doc: dict, errors: list[str]) -> None:
    fid = doc.get("fixture_id", "?")
    design = doc.get("design") or {}
    dh = design.get("design_hash")
    comp = doc.get("compilation")
    ev = doc.get("evaluation")
    req = doc.get("requirements")
    opt = doc.get("optimization")
    # Study rule: an optimization fixture spans base intent + winning
    # design. design/opt.base bind the BASE; comp/eval/req bind ONE
    # winner hash that must appear among the study candidates. A study
    # claiming a winner outside its own candidate set is incoherent.
    candidate_hashes = set()
    if isinstance(opt, dict):
        for row in opt.get("candidates", []):
            h = (row.get("evaluation_ids") or {}).get("design_hash")
            if h:
                candidate_hashes.add(h)
    product_hashes = {
        slot for slot in (
            (comp or {}).get("design_hash"),
            (ev or {}).get("design_hash"),
            (req or {}).get("design_hash"),
        ) if slot}
    # The winner hash is exempt from single-design equality below, but
    # never from the completeness checks (EVALUATED slots stay fully
    # audited whichever design they bind).
    winner_ok: set[str] = set()
    if candidate_hashes and product_hashes - {dh}:
        extra = product_hashes - {dh}
        if len(extra) != 1 or not extra <= candidate_hashes:
            errors.append(
                f"{fid}: study product views must share one winner hash "
                f"from the study candidates, got {sorted(extra)}")
        else:
            winner_ok = extra
    if comp and comp.get("design_hash") != dh \
            and comp.get("design_hash") not in winner_ok:
        errors.append(f"{fid}: compilation.design_hash != design.design_hash")
    if ev:
        if ev.get("design_hash") != dh \
                and ev.get("design_hash") not in winner_ok:
            errors.append(f"{fid}: evaluation.design_hash != design.design_hash")
        if ev.get("status") == "EVALUATED":
            for key in (
                "message_artifact_id",
                "physical_traffic_id",
                "backend_producer",
                "evidence",
                "performance_result_id",
                "network_traffic_window",
            ):
                if ev.get(key) is None:
                    errors.append(f"{fid}: EVALUATED missing {key}")
        if ev.get("status") in ("BACKEND_UNAVAILABLE", "FAILED", "UNSUPPORTED"):
            if ev.get("metrics") is not None:
                errors.append(
                    f"{fid}: {ev['status']} must not carry metrics "
                    "(absent metrics are absent, never zero-filled)"
                )
    if req:
        if req.get("design_hash") != dh \
                and req.get("design_hash") not in winner_ok:
            errors.append(f"{fid}: requirements.design_hash != design.design_hash")
        if ev and ev.get("performance_result_id") and (
            req.get("performance_result_id") != ev["performance_result_id"]
        ):
            errors.append(f"{fid}: requirements.performance_result_id != evaluation's")
    if opt:
        if opt.get("base_design_hash") != dh:
            errors.append(
                f"{fid}: optimization.base_design_hash != design.design_hash")
        check_study_coherence(opt, fid, errors)


def check_study_coherence(opt: dict, fid: str, errors: list[str]) -> None:
    """v2 study semantics the engine guarantees; mirrored (C-1/C-5).

    Schemas accept broad shapes; these are the invariants that make the
    three authorities renderable without the UI inferring anything.
    """
    label = f"{fid}:optimization"
    if opt.get("contract_version") != 2:
        errors.append(f"{label}: study must declare contract_version 2")
        return
    definition = opt.get("definition") or {}
    for objective in definition.get("objectives", []):
        if objective.get("direction") not in OBJECTIVE_DIRECTIONS:
            errors.append(
                f"{label}: objective {objective.get('metric')!r} direction "
                f"{objective.get('direction')!r} not in "
                f"{sorted(OBJECTIVE_DIRECTIONS)}")
    for constraint in definition.get("constraints", []):
        if constraint.get("op") not in CONSTRAINT_OPS:
            errors.append(
                f"{label}: constraint {constraint.get('metric')!r} op "
                f"{constraint.get('op')!r} not in {sorted(CONSTRAINT_OPS)}")
    objective_metrics = {o.get("metric")
                         for o in definition.get("objectives", [])}
    constraint_metrics = {c.get("metric")
                          for c in definition.get("constraints", [])}
    result_class = opt.get("result_class")
    if result_class not in RESULT_CLASSES:
        errors.append(f"{label}: unknown result_class {result_class!r}")
    if result_class == "CERTIFIED_PRODUCT":
        if not opt.get("metric_registry_id"):
            errors.append(
                f"{label}: CERTIFIED_PRODUCT requires metric_registry_id")
        if not opt.get("metric_registry_version"):
            errors.append(
                f"{label}: CERTIFIED_PRODUCT requires "
                "metric_registry_version")
    elif result_class == "ANALYTIC_RESEARCH":
        if opt.get("metric_registry_id") is not None \
                or opt.get("metric_registry_version") is not None:
            errors.append(
                f"{label}: ANALYTIC_RESEARCH must not bind a certified "
                "metric registry identity")
    candidates = opt.get("candidates", [])
    by_id = {c.get("candidate_id"): c for c in candidates}
    members = {c.get("candidate_id") for c in candidates
               if c.get("pareto_member")}
    pareto_ids = set(opt.get("pareto_ids", []))
    if members != pareto_ids:
        errors.append(
            f"{label}: pareto_ids {sorted(pareto_ids)} != Pareto members "
            f"{sorted(members)}")
    selected = opt.get("selected_candidate_id")
    if selected is not None:
        if selected not in by_id:
            errors.append(
                f"{label}: selected_candidate_id {selected!r} is not a "
                "candidate")
        elif not by_id[selected].get("pareto_member"):
            errors.append(
                f"{label}: selected candidate {selected!r} is not a Pareto "
                "member")
    for row in candidates:
        cid = row.get("candidate_id", "?")
        clabel = f"{label}.{cid}"
        if row.get("compilation_status") not in COMPILATION_STATUSES:
            errors.append(
                f"{clabel}: unknown compilation_status "
                f"{row.get('compilation_status')!r}")
        if row.get("evaluation_status") not in CANDIDATE_EVALUATION_STATUSES:
            errors.append(
                f"{clabel}: unknown evaluation_status "
                f"{row.get('evaluation_status')!r}")
        if row.get("evaluation_authority") not in CANDIDATE_AUTHORITIES:
            errors.append(
                f"{clabel}: unknown evaluation_authority "
                f"{row.get('evaluation_authority')!r}")
        verdicts = row.get("constraint_verdicts") or {}
        for metric, verdict in verdicts.items():
            if verdict not in CONSTRAINT_VERDICTS:
                errors.append(
                    f"{clabel}: constraint {metric!r} verdict {verdict!r} "
                    f"is not one of {sorted(CONSTRAINT_VERDICTS)} "
                    "(booleans are a lossy v1 shape, never v2)")
        availability = row.get("objective_availability") or {}
        for metric, state in availability.items():
            if state not in OBJECTIVE_STATES:
                errors.append(
                    f"{clabel}: objective {metric!r} availability {state!r} "
                    f"is not one of {sorted(OBJECTIVE_STATES)}")
        missing_objectives = objective_metrics - set(availability)
        if missing_objectives:
            errors.append(
                f"{clabel}: requested objective(s) "
                f"{sorted(missing_objectives)} have no explicit "
                "availability state")
        missing_constraints = constraint_metrics - set(verdicts)
        if missing_constraints:
            errors.append(
                f"{clabel}: declared constraint(s) "
                f"{sorted(missing_constraints)} have no verdict")
        values = row.get("objective_values") or {}
        for metric, value in values.items():
            if availability.get(metric) != "MEASURED":
                errors.append(
                    f"{clabel}: objective {metric!r} carries a value while "
                    f"availability is {availability.get(metric)!r}")
        eligible = row.get("pareto_eligible")
        reason = row.get("eligibility_reason")
        if eligible and reason is not None:
            errors.append(
                f"{clabel}: pareto_eligible=true with an eligibility_reason "
                "(eligible rows carry no reason)")
        if not eligible and not reason:
            errors.append(
                f"{clabel}: pareto_eligible=false without an "
                "eligibility_reason (ineligibility must be typed)")
        if row.get("pareto_member") and not eligible:
            errors.append(
                f"{clabel}: pareto_member=true without pareto_eligible")
        perf = (row.get("evaluation_ids") or {}).get("performance_result_id")
        if row.get("evaluation_status") == "EVALUATED" and not perf:
            errors.append(f"{clabel}: EVALUATED without performance_result_id")
        if eligible:
            if row.get("evaluation_status") != "EVALUATED":
                errors.append(
                    f"{clabel}: eligible candidate is not EVALUATED")
            if row.get("evaluation_authority") != "certified-backend":
                errors.append(
                    f"{clabel}: eligible candidate's evaluation authority "
                    f"{row.get('evaluation_authority')!r} is not "
                    "certified-backend")
            product = row.get("product_requirements") or {}
            if product.get("satisfied") is not True:
                errors.append(
                    f"{clabel}: eligible candidate's product requirements "
                    "are not satisfied (UNMEASURABLE never passes)")
            for metric in objective_metrics:
                if availability.get(metric) != "MEASURED":
                    errors.append(
                        f"{clabel}: eligible candidate has an unmeasured "
                        f"objective {metric!r}")
            for metric in constraint_metrics:
                if verdicts.get(metric) != "SATISFIED":
                    errors.append(
                        f"{clabel}: eligible candidate has constraint "
                        f"{metric!r}={verdicts.get(metric)!r}")
        if row.get("evaluation_status") == "EVALUATED" and \
                (row.get("product_requirements") or {}).get("satisfied") \
                is False and not row.get("evaluation_reason"):
            errors.append(
                f"{clabel}: EVALUATED with failed product requirements must "
                "carry an evaluation_reason")


def check_realizable(doc: dict, errors: list[str]) -> None:
    """Semantic values must be producible by the real engine."""
    fid = doc.get("fixture_id", "?")
    design = doc.get("design")
    if not design:
        return
    wl = design.get("workload") or {}
    if wl.get("model_family") not in MODEL_FAMILIES:
        errors.append(
            f"{fid}: model_family {wl.get('model_family')!r} is not a "
            f"ModelFamily value {sorted(MODEL_FAMILIES)}"
        )
    if wl.get("serving_mode") is not None and wl["serving_mode"] not in SERVING_MODES:
        errors.append(
            f"{fid}: serving_mode {wl['serving_mode']!r} is not a ServingMode "
            f"value {sorted(SERVING_MODES)}"
        )
    for req in design.get("requirements", []):
        if req.get("qos_class") not in QOS_CLASSES:
            errors.append(
                f"{fid}: qos_class {req.get('qos_class')!r} is not a QoSClass "
                f"value {sorted(QOS_CLASSES)}"
            )
    for agent in design.get("agents", []):
        if agent.get("kind") not in AGENT_KINDS:
            errors.append(
                f"{fid}: agent kind {agent.get('kind')!r} is not an AgentKind "
                f"value {sorted(AGENT_KINDS)}"
            )
    guided = design.get("noc_guided") or {}
    if guided.get("topology_family") is not None and (
        guided["topology_family"] not in TOPOLOGY_FAMILIES
    ):
        errors.append(
            f"{fid}: topology_family {guided['topology_family']!r} is not a "
            f"TopologyFamily value {sorted(TOPOLOGY_FAMILIES)}"
        )
    if guided.get("arbitration") is not None and (
        guided["arbitration"] not in ARBITRATION_ALIASES
    ):
        errors.append(
            f"{fid}: arbitration {guided['arbitration']!r} is not a known "
            f"allocator alias {sorted(ARBITRATION_ALIASES)}"
        )
    comp = doc.get("compilation")
    if (comp and comp.get("status") == "COMPILED"
            and guided.get("rcu_enabled") is True):
        errors.append(
            f"{fid}: rcu_enabled=True with status COMPILED is impossible — "
            "model/resolved_fabric.py refuses rcu_enabled=True as UNSUPPORTED"
        )
    # materialize_family sizing: radix pins k, and k*k*concentration seats
    # must cover the full agent count for the fabric to exist at all.
    radix = guided.get("radix")
    concentration = guided.get("concentration")
    if (comp and comp.get("status") == "COMPILED"
            and isinstance(radix, int) and isinstance(concentration, int)):
        endpoints = sum(a.get("count", 0) for a in design.get("agents", []))
        seats = radix * radix * concentration
        if seats < endpoints:
            errors.append(
                f"{fid}: radix {radix} × concentration {concentration} "
                f"provides {seats} seats but {endpoints} agents must attach — "
                "the compiler would refuse (UNSUPPORTED), never COMPILE"
            )


def _study_self_tests() -> list[tuple[str, dict, str]]:
    """Schema-shaped v2 studies the engine can never emit.

    Each case must be rejected by ``check_study_coherence``; otherwise
    the three-state gate is decorative.
    """

    def candidate(**over):
        row = {
            "candidate_id": "cand_test",
            "guided_patch": {"link_width": 64},
            "evaluation_ids": {
                "design_hash": "sha256:" + "a" * 64,
                "performance_result_id": "b" * 64,
                "requirement_report_id": "c" * 64,
            },
            "product_requirements": {"satisfied": True, "verdicts": []},
            "objective_values": {"completion_cycles": 100.0},
            "objective_availability": {"completion_cycles": "MEASURED"},
            "constraint_verdicts": {"completion_cycles": "SATISFIED"},
            "evaluation_authority": "certified-backend",
            "compilation_status": "COMPILED",
            "evaluation_status": "EVALUATED",
            "evaluation_reason": None,
            "eligibility_reason": None,
            "pareto_eligible": True,
            "pareto_member": True,
        }
        row.update(over)
        return row

    def study(**over):
        body = {
            "contract_version": 2,
            "result_class": "CERTIFIED_PRODUCT",
            "metric_registry_id": "d" * 64,
            "metric_registry_version": "certified-builtin-v1",
            "optimization_result_id": "e" * 64,
            "base_design_hash": "sha256:" + "f" * 64,
            "definition": {
                "definition_id": "0" * 64,
                "objectives": [{"metric": "completion_cycles",
                                "direction": "MIN"}],
                "constraints": [{"metric": "completion_cycles",
                                 "op": "<=", "threshold": 200.0}],
                "method": "grid",
                "selection": "min_first_objective",
                "budget": {},
            },
            "candidates": [candidate()],
            "pareto_ids": ["cand_test"],
            "selected_candidate_id": "cand_test",
            "selection_rationale": "picked",
        }
        body.update(over)
        return body

    return [
        ("boolean constraint verdict",
         study(candidates=[candidate(constraint_verdicts={
             "completion_cycles": True})]), "constraint"),
        ("eligible with VIOLATED constraint",
         study(candidates=[candidate(constraint_verdicts={
             "completion_cycles": "VIOLATED"})]), "constraint"),
        ("eligible with UNMEASURABLE objective",
         study(candidates=[candidate(
             objective_availability={"completion_cycles": "UNMEASURABLE"},
             objective_values={})]), "unmeasured objective"),
        ("eligible without certified authority",
         study(candidates=[candidate(
             evaluation_authority="analytic-fake")]), "authority"),
        ("eligible with UNMEASURABLE product requirements",
         study(candidates=[candidate(product_requirements={
             "satisfied": None, "verdicts": []})]), "product requirements"),
        ("pareto member without eligibility",
         study(candidates=[candidate(pareto_eligible=False, pareto_member=True,
                                     eligibility_reason="nope")]), "pareto"),
        ("untyped ineligibility",
         study(candidates=[candidate(pareto_eligible=False,
                                     pareto_member=False,
                                     eligibility_reason=None)],
               pareto_ids=[], selected_candidate_id=None),
         "eligibility_reason"),
        ("certified result without registry identity",
         study(metric_registry_id=None), "metric_registry_id"),
        ("pareto_ids disagree with members",
         study(pareto_ids=[]), "pareto_ids"),
        ("unmeasured objective carrying a value",
         study(candidates=[candidate(
             objective_values={"completion_cycles": 10.0},
             objective_availability={"completion_cycles": "UNMEASURABLE"},
             pareto_eligible=False, pareto_member=False,
             eligibility_reason="unmeasured")],
             pareto_ids=[], selected_candidate_id=None),
         "availability"),
    ]


def self_test() -> list[str]:
    """Prove the realizability gate rejects the impossibilities it exists for.

    Each case is a document the frozen schemas would accept but the engine
    cannot produce. If any case passes silently, the gate is broken.
    """
    errors: list[str] = []
    base_design = {
        "workload": {"model_family": "dense_transformer", "serving_mode": "mixed"},
        "requirements": [{"qos_class": "latency_critical"}],
        "agents": [{"kind": "compute_tile", "count": 64},
                   {"kind": "hbm_controller", "count": 8},
                   {"kind": "nic", "count": 2},
                   {"kind": "peripheral", "count": 4}],
        "noc_guided": {"topology_family": "mesh", "radix": 5,
                       "concentration": 4, "arbitration": "round_robin",
                       "rcu_enabled": False},
    }
    compiled = {"status": "COMPILED"}

    def mutated(**over):
        design = copy.deepcopy(base_design)
        for path, value in over.items():
            if path == "rcu_enabled":
                design["noc_guided"]["rcu_enabled"] = value
            elif path == "radix":
                design["noc_guided"]["radix"] = value
            else:
                design[path] = value
        return {"fixture_id": "self-test", "design": design,
                "compilation": compiled}

    cases = {
        "rcu_enabled=True with COMPILED": mutated(rcu_enabled=True),
        "invented model_family": mutated(workload={"model_family": "llama3"}),
        "invented agent kind": mutated(agents=[{"kind": "compute", "count": 64}]),
        "invented qos_class": mutated(requirements=[{"qos_class": "latency_sensitive"}]),
        "uppercase topology value": mutated(
            noc_guided={"topology_family": "MESH", "radix": 5,
                        "concentration": 4, "rcu_enabled": False}),
        "impossible sizing": mutated(radix=3),
    }
    for label, doc in cases.items():
        found: list[str] = []
        check_realizable(doc, found)
        if not found:
            errors.append(f"self-test: gate failed to reject {label}")
    for label, opt, needle in _study_self_tests():
        found = []
        check_study_coherence(opt, "self-test", found)
        if not found:
            errors.append(f"self-test: study gate failed to reject {label}")
    return errors


# ── provisioned backend proof (C-3/C-4) ─────────────────────────────────────

def provisioned_environment() -> tuple[bool, str]:
    """A qualified BookSim is the provisioning boundary (C-3)."""
    if not DSE_DIR.exists():
        return False, f"engine package not found at {DSE_DIR}"
    if str(DSE_DIR) not in sys.path:
        sys.path.insert(0, str(DSE_DIR))
    try:
        from veritx_dse.core.paths import REPO as engine_repo
        from veritx_dse.simulation.booksim import find_booksim_bin
    except Exception as exc:  # pragma: no cover - environment dependent
        return False, (f"cannot import the engine ({type(exc).__name__}: "
                       f"{exc})")
    if Path(engine_repo).resolve() != REPO.resolve():
        return False, (f"engine package resolves to a different checkout "
                       f"({engine_repo}) than this workspace ({REPO})")
    try:
        binary = find_booksim_bin(REPO)
    except Exception as exc:  # pragma: no cover - environment dependent
        return False, (f"no qualified BookSim producer "
                       f"({type(exc).__name__}: {exc})")
    path = Path(str(binary))
    if not path.is_file() or not os.access(path, os.X_OK):
        return False, f"BookSim producer {path} is not an executable file"
    # The offline-demo fixtures are regenerated through an engine helper that
    # is absent on this branch; the live Studio product path is the gateway,
    # so regeneration is not a live-flow blocker. Report it as unprovisioned
    # rather than letting a ModuleNotFoundError escape.
    import importlib.util
    if importlib.util.find_spec(
            "veritx_dse.application.product_evaluator") is None:
        return False, (
            "offline-demo fixture generator requires "
            "veritx_dse.application.product_evaluator (absent on this "
            "branch); the live Studio path is the gateway")
    return True, str(path)


def _diff_paths(a, b, prefix: str = "") -> list[str]:
    if isinstance(a, dict) and isinstance(b, dict):
        paths: list[str] = []
        for key in sorted(set(a) | set(b)):
            if key not in a or key not in b:
                paths.append(f"{prefix}.{key}")
            else:
                paths.extend(_diff_paths(a[key], b[key], f"{prefix}.{key}"))
        return paths
    if isinstance(a, list) and isinstance(b, list):
        if len(a) != len(b):
            return [f"{prefix} (length {len(a)} != {len(b)})"]
        paths = []
        for i, (x, y) in enumerate(zip(a, b)):
            paths.extend(_diff_paths(x, y, f"{prefix}[{i}]"))
        return paths
    if a != b:
        return [prefix or "<root>"]
    return []


def _is_provenance_path(path: str) -> bool:
    return any(pattern.match(path) for pattern in _PROVENANCE_DIFF_PATTERNS)


def compare_bytes(committed: Path, regenerated: Path,
                  ) -> tuple[bool, list[str], list[str]]:
    """Byte-for-byte comparison with defect classification.

    Returns (identical, provenance_paths, semantic_paths). Any semantic
    path is a hard mismatch; a provenance-only difference is the known
    engine defect and is reported, never blessed.
    """
    if committed.read_bytes() == regenerated.read_bytes():
        return True, [], []
    committed_doc = json.loads(committed.read_bytes())
    regenerated_doc = json.loads(regenerated.read_bytes())
    differences = _diff_paths(committed_doc, regenerated_doc)
    provenance = [p for p in differences if _is_provenance_path(p)]
    semantic = [p for p in differences if not _is_provenance_path(p)]
    return False, provenance, semantic


def prove_engine_semantics(docs: dict[str, dict]) -> list[str]:
    """Prove the EVALUATED fixture + report + certified study (C-3).

    These assertions run against ENGINE-PRODUCED documents, so they prove
    backend evaluation and real optimization happened — not schema shape.
    """
    errors: list[str] = []
    comp = docs.get("compiled-mesh", {}).get("compilation") or {}
    if comp.get("status") != "COMPILED":
        errors.append("compiled-mesh: engine did not produce COMPILED")
    if comp.get("certificate_overall") != "PASS":
        errors.append("compiled-mesh: engine certificate is not PASS")
    obligations = comp.get("obligations") or []
    if len(obligations) != 10 or any(
            o.get("status") != "PASS" for o in obligations):
        errors.append(
            "compiled-mesh: engine did not prove 10/10 obligations")

    invalid = docs.get("invalid-design", {}).get("compilation") or {}
    if invalid.get("status") not in ("INVALID", "UNSUPPORTED"):
        errors.append("invalid-design: engine did not refuse the design")

    unavailable = docs.get("backend-unavailable", {}).get("evaluation") or {}
    if unavailable.get("status") != "BACKEND_UNAVAILABLE":
        errors.append(
            "backend-unavailable: engine did not produce BACKEND_UNAVAILABLE")
    if unavailable.get("metrics") is not None:
        errors.append("backend-unavailable: refusal carries metrics")

    evaluated = docs.get("evaluated-design", {})
    ev = evaluated.get("evaluation") or {}
    report = evaluated.get("requirements") or {}
    if ev.get("status") != "EVALUATED":
        errors.append("evaluated-design: engine did not EVALUATE")
    if not ev.get("metrics"):
        errors.append("evaluated-design: engine produced no metrics")
    if not (ev.get("network_traffic_window") or {}).get("window_cycles"):
        errors.append("evaluated-design: engine produced no network window")
    if not ev.get("performance_result_id"):
        errors.append("evaluated-design: no performance_result_id")
    if not report.get("entries"):
        errors.append("evaluated-design: engine produced no RequirementReport")
    if report.get("performance_result_id") != ev.get("performance_result_id"):
        errors.append(
            "evaluated-design: RequirementReport does not bind the evaluated "
            "performance result")
    if report.get("design_hash") != ev.get("design_hash"):
        errors.append(
            "evaluated-design: RequirementReport design_hash mismatch")
    binding = [e for e in report.get("entries", []) if e.get("binding")]
    if not binding:
        errors.append("evaluated-design: RequirementReport has no binding entry")
    if any(e.get("verdict") == "UNMEASURABLE" for e in binding):
        errors.append(
            "evaluated-design: binding requirement is UNMEASURABLE after a "
            "successful evaluation")

    study_doc = docs.get("optimization-study", {})
    opt = study_doc.get("optimization") or {}
    if opt.get("contract_version") != 2:
        errors.append("optimization-study: engine did not project contract v2")
    if opt.get("result_class") != "CERTIFIED_PRODUCT":
        errors.append(
            "optimization-study: engine did not produce CERTIFIED_PRODUCT "
            "(only Optimizer.optimize_certified may)")
    registry_id = opt.get("metric_registry_id")
    try:
        from veritx_dse.optimization.metric_registry import (
            CERTIFIED_METRIC_REGISTRY,
        )
    except Exception as exc:  # pragma: no cover - import boundary
        errors.append(f"optimization-study: cannot import the registry ({exc})")
    else:
        expected = CERTIFIED_METRIC_REGISTRY.registry_id()
        if registry_id != expected:
            errors.append(
                f"optimization-study: metric_registry_id {registry_id!r} != "
                f"engine registry {expected!r}")
        if opt.get("metric_registry_version") != \
                CERTIFIED_METRIC_REGISTRY.version:
            errors.append(
                "optimization-study: metric_registry_version mismatch")
    rows = opt.get("candidates") or []
    if not opt.get("pareto_ids"):
        errors.append("optimization-study: engine produced no Pareto member")
    if opt.get("selected_candidate_id") not in set(opt.get("pareto_ids", [])):
        errors.append(
            "optimization-study: engine selected a non-Pareto candidate")
    verdicts = {v for row in rows
                for v in (row.get("constraint_verdicts") or {}).values()}
    if not {"SATISFIED", "VIOLATED", "UNMEASURABLE"} <= verdicts:
        errors.append(
            "optimization-study: engine output does not demonstrate the "
            f"three-state constraint taxonomy (got {sorted(verdicts)})")
    if not any((row.get("product_requirements") or {}).get("satisfied")
               is False for row in rows):
        errors.append(
            "optimization-study: no requirement-refused candidate")
    if not any(row.get("evaluation_status") == "EVALUATED"
               and not row.get("pareto_eligible") for row in rows):
        errors.append(
            "optimization-study: no evaluated-but-ineligible candidate")
    if not any("UNMEASURABLE" in (row.get("objective_availability")
                                  or {}).values() for row in rows):
        errors.append(
            "optimization-study: no objective-unavailable candidate")
    return errors


def check_engine_realizability() -> tuple[list[str], list[str], int, int, int]:
    """Regenerate with the engine tool and compare BYTE-FOR-BYTE (C-4).

    Returns (semantic_proof_errors, byte_errors, byte_identical,
             provenance_only, semantic_mismatch).
    """
    if str(DSE_DIR) not in sys.path:
        sys.path.insert(0, str(DSE_DIR))
    try:
        from veritx_dse.tools import generate_studio_fixtures as engine
    except Exception as exc:  # pragma: no cover - environment dependent
        return ([f"ENGINE CHECK FAILED: cannot import {ENGINE_TOOL_MODULE}: "
                 f"{type(exc).__name__}: {exc}"], [], 0, 0, 0)
    proof_errors: list[str] = []
    byte_errors: list[str] = []
    identical = provenance_only = semantic = 0
    with tempfile.TemporaryDirectory(prefix="studio-fixture-regen-") as tmp:
        tmp_dir = Path(tmp)
        # The engine tool preserves title/description from the existing
        # envelope, so seed the temp dir with the committed fixtures.
        for stem in EXPECTED_FIXTURES:
            shutil.copy2(FIXTURE_DIR / f"{stem}.json", tmp_dir / f"{stem}.json")
        old_fixture_dir = engine.FIXTURE_DIR
        engine.FIXTURE_DIR = str(tmp_dir)
        try:
            engine.main()
        except Exception as exc:
            return ([f"ENGINE CHECK FAILED: fixture regeneration raised "
                     f"{type(exc).__name__}: {exc}"], [], 0, 0, 0)
        finally:
            engine.FIXTURE_DIR = old_fixture_dir
        docs: dict[str, dict] = {}
        for stem in sorted(EXPECTED_FIXTURES):
            regenerated = tmp_dir / f"{stem}.json"
            if not regenerated.exists():
                proof_errors.append(
                    f"{stem}.json: engine regeneration produced no file")
                continue
            docs[stem] = json.loads(regenerated.read_bytes())
        if not proof_errors:
            proof_errors.extend(prove_engine_semantics(docs))
        for stem in sorted(EXPECTED_FIXTURES):
            committed = FIXTURE_DIR / f"{stem}.json"
            regenerated = tmp_dir / f"{stem}.json"
            if not regenerated.exists():
                continue
            is_identical, prov, semantic_paths = compare_bytes(
                committed, regenerated)
            if is_identical:
                identical += 1
                print(f"PASS {stem}.json (engine byte-identical)")
                continue
            if semantic_paths:
                semantic += 1
                byte_errors.append(
                    f"{stem}.json differs from engine regeneration on "
                    f"SEMANTIC field(s): {', '.join(semantic_paths[:10])}"
                    + (" ..." if len(semantic_paths) > 10 else ""))
                continue
            if not prov:
                byte_errors.append(
                    f"{stem}.json differs in bytes while the parsed content "
                    "is equal — serialization/formatting drift; the writer "
                    "must be deterministic")
                continue
            provenance_only += 1
            byte_errors.append(
                f"ENGINE DEFECT (REPORTED, NOT NORMALIZED) {stem}.json: a "
                "byte difference lands on runtime-provenance-derived "
                "identity paths (evidence.backend_dir/wall_time_s/tool "
                "identity leaked back into the scientific digest). "
                "Byte-for-byte reproducibility FAILS on: "
                + ", ".join(prov)
                + ". This is an engine-side evidence-v2 contract "
                "regression (backend/evidence.py + backend/booksim.py).")
    return proof_errors, byte_errors, identical, provenance_only, semantic


# ── fast-path validation ────────────────────────────────────────────────────

def validate_one(path: Path,
                 validators: dict[tuple[Path, str], Draft202012Validator],
                 ) -> list[str]:
    errors: list[str] = []
    try:
        doc = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError) as exc:
        return [f"{path.name}: unreadable ({exc})"]
    for view, (schema_dir, schema_name) in VIEW_SCHEMAS.items():
        payload = doc.get(view)
        if payload is None:
            continue
        for err in validators[(schema_dir, schema_name)].iter_errors(payload):
            errors.append(f"{path.name}:{view}: {list(err.path)}: {err.message}")
    if not errors:
        check_linkage(doc, errors)
        check_realizable(doc, errors)
    return errors


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate Studio fixtures (schema + linkage + "
                    "engine-vocabulary fast path; provisioned backend proof "
                    "with --engine).")
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--engine", action="store_true",
        help="force the provisioned backend proof (requires qualified "
             "BookSim; fails loudly when absent)")
    group.add_argument(
        "--skip-engine", action="store_true",
        help="skip the provisioned backend proof (offline fast path only)")
    return parser.parse_args(argv)


def engine_mode_default() -> bool:
    """Engine proof is ON by default in CI, OFF on an offline workstation."""
    return bool(os.environ.get("CI") or os.environ.get("GITHUB_ACTIONS"))


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    engine_mode = args.engine or (not args.skip_engine and engine_mode_default())

    missing_schemas = [
        schema_dir / schema_name
        for schema_dir, schema_name in VIEW_SCHEMAS.values()
        if not (schema_dir / schema_name).is_file()
    ]
    if missing_schemas:
        print("FAIL: missing contract schema(s): "
              + ", ".join(str(p) for p in missing_schemas))
        return 1
    validators = {
        key: Draft202012Validator(load_schema(*key))
        for key in VIEW_SCHEMAS.values()
    }
    print("View contracts: optimization -> "
          f"{STUDY_SCHEMA_V2.relative_to(REPO)} (authoritative v2); "
          "design/compilation/evaluation/requirements -> contracts/srota/v1/")

    errors: list[str] = self_test()
    if errors:
        print("FAIL (realizability gate self-test):")
        for e in errors:
            print(f"  - {e}")
        return 1
    found = sorted(p.stem for p in FIXTURE_DIR.glob("*.json"))
    errors = []
    if set(found) != EXPECTED_FIXTURES:
        errors.append(
            f"fixture set mismatch: found {found}, expected "
            f"{sorted(EXPECTED_FIXTURES)}")
    for stem in sorted(EXPECTED_FIXTURES):
        path = FIXTURE_DIR / f"{stem}.json"
        if not path.exists():
            errors.append(f"missing fixture {stem}.json")
            continue
        view_errors = validate_one(path, validators)
        if view_errors:
            errors.extend(view_errors)
        else:
            print(f"PASS {stem}.json (schema + linkage + engine vocabulary)")
    if errors:
        print("FAIL:")
        for e in errors:
            print(f"  - {e}")
        return 1
    print(f"Fast checks passed for {len(EXPECTED_FIXTURES)}/"
          f"{len(EXPECTED_FIXTURES)} fixtures "
          "(schemas + linkage + engine vocabulary).")

    if not engine_mode:
        print(FAST_LINE)
        return 0

    provisioned, detail = provisioned_environment()
    if not provisioned:
        print(f"ENGINE PROOF FAILED: {detail}")
        print(FAST_LINE)
        return 1
    print(f"PROVISIONED: qualified BookSim at {detail} — proving backend "
          "realizability through the engine gateways "
          f"({ENGINE_TOOL_MODULE}) ...")
    engine_errors, byte_errors, identical, provenance_only, semantic = \
        check_engine_realizability()
    if engine_errors:
        print("FAIL (provisioned backend proof):")
        for e in engine_errors:
            print(f"  - {e}")
        return 1
    print(f"Engine objects verified: EVALUATED fixture + RequirementReport + "
          "CERTIFIED_PRODUCT OptimizationStudy through the engine gateways.")
    if byte_errors:
        print("FAIL (provisioned byte-for-byte reproducibility):")
        for e in byte_errors:
            print(f"  - {e}")
        return 1
    print(f"Bytes: {identical} identical, {provenance_only} provenance-only "
          f"(reported defects), {semantic} semantic mismatches.")
    print(PROVEN_LINE)
    return 0


if __name__ == "__main__":
    sys.exit(main())
