#!/usr/bin/env python3
"""gen_rtl_2die.py — Extended RTL generator with multi-die + AXI4 support.

Extends gen_rtl.py with:
  1. emit_2die_wrapper() — generates noc_2die.sv with CDC FIFO bridges
  2. emit_axi4_wrapper() — generates axi4_nic.sv for standard AXI4 protocol
  3. emit_2die_tb() — testbench for multi-die verification

Usage:
  python3 gen_rtl_2die.py --anynet runs/booksim/2die_mesh.anynet --outdir /tmp/rtl_2die --bridges 32
  python3 gen_rtl_2die.py --anynet runs/booksim/2die_mesh.anynet --outdir /tmp/rtl_2die --bridges 32 --axi4

The original gen_rtl.py is NOT modified. This file imports and extends it.
"""
import argparse
import math
import sys
from pathlib import Path

# Import the original generator's functions
sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_rtl import (
    parse_anynet, emit_pkg, emit_top, emit_makefile,
    dijkstra_tables, tree_tables
)


# ── Multi-die wrapper ─────────────────────────────────────────────────────

def emit_2die_wrapper(outdir, n_per_die, bridges):
    """Generate noc_2die.sv: two noc_top instances connected by CDC FIFO bridges."""
    num_bridges = len(bridges)
    flit_w = 64
    fifo_depth = 8
    fifo_stages = 2

    lines = [
        "// Generated by gen_rtl_2die.py — 2-die NoC with %d UCIe bridges" % num_bridges,
        "// Die 0: %d routers, Die 1: %d routers" % (n_per_die, n_per_die),
        "// Bridges: CDC FIFOs with gray-code synchronization",
        "",
        "module noc_2die (",
        "  input  logic clk_0,        // Die 0 clock",
        "  input  logic clk_1,        // Die 1 clock",
        "  input  logic rst_n_0,      // Die 0 reset",
        "  input  logic rst_n_1,      // Die 1 reset",
    ]

    # Die 0 local ports
    for r in range(n_per_die):
        lines.extend([
            "  // Die 0, Router %d" % r,
            "  output noc_pkg::flit_raw_t die0_local_out_flit_%d," % r,
            "  output logic       die0_local_out_valid_%d," % r,
            "  input  logic       die0_local_out_ready_%d," % r,
            "  input  noc_pkg::flit_raw_t die0_local_in_flit_%d," % r,
            "  input  logic       die0_local_in_valid_%d," % r,
            "  output logic       die0_local_in_ready_%d," % r,
        ])

    # Die 1 local ports
    for r in range(n_per_die):
        lines.extend([
            "  // Die 1, Router %d" % r,
            "  output noc_pkg::flit_raw_t die1_local_out_flit_%d," % r,
            "  output logic       die1_local_out_valid_%d," % r,
            "  input  logic       die1_local_out_ready_%d," % r,
            "  input  noc_pkg::flit_raw_t die1_local_in_flit_%d," % r,
            "  input  logic       die1_local_in_valid_%d," % r,
            "  output logic       die1_local_in_ready_%d," % r,
        ])

    lines.append(");")
    lines.append("")

    # Die 0 instance
    lines.append("  // === Die 0 ===")
    lines.append("  noc_top die0 (")
    lines.append("    .clk(clk_0),")
    lines.append("    .rst_n(rst_n_0),")
    for r in range(n_per_die):
        comma = "," if r < n_per_die - 1 else ""
        lines.append("    .local_out_flit_%d(die0_local_out_flit_%d)," % (r, r))
        lines.append("    .local_out_valid_%d(die0_local_out_valid_%d)," % (r, r))
        lines.append("    .local_out_ready_%d(die0_local_out_ready_%d)," % (r, r))
        lines.append("    .local_in_flit_%d(die0_local_in_flit_%d)," % (r, r))
        lines.append("    .local_in_valid_%d(die0_local_in_valid_%d)," % (r, r))
        lines.append("    .local_in_ready_%d(die0_local_in_ready_%d)%s" % (r, r, comma))
    lines.append("  );")
    lines.append("")

    # Die 1 instance
    lines.append("  // === Die 1 ===")
    lines.append("  noc_top die1 (")
    lines.append("    .clk(clk_1),")
    lines.append("    .rst_n(rst_n_1),")
    for r in range(n_per_die):
        comma = "," if r < n_per_die - 1 else ""
        lines.append("    .local_out_flit_%d(die1_local_out_flit_%d)," % (r, r))
        lines.append("    .local_out_valid_%d(die1_local_out_valid_%d)," % (r, r))
        lines.append("    .local_out_ready_%d(die1_local_out_ready_%d)," % (r, r))
        lines.append("    .local_in_flit_%d(die1_local_in_flit_%d)," % (r, r))
        lines.append("    .local_in_valid_%d(die1_local_in_valid_%d)," % (r, r))
        lines.append("    .local_in_ready_%d(die1_local_in_ready_%d)%s" % (r, r, comma))
    lines.append("  );")
    lines.append("")

    # CDC FIFO bridges
    lines.append("  // === UCIe Bridges (CDC FIFOs) ===")
    lines.append("")

    for i, (r0, r1, latency) in enumerate(bridges):
        lines.extend([
            "  // Bridge %d: die0.router%d <-> die1.router%d (%d cyc)" % (i, r0, r1, latency),
            "  logic bridge_%d_fwd_full, bridge_%d_fwd_rd_en, bridge_%d_fwd_rd_valid, bridge_%d_fwd_empty;" % (i, i, i, i),
            "  logic [%d:0] bridge_%d_fwd_rd_data;" % (flit_w - 1, i),
            "",
            "  cdc_fifo #(",
            "    .DATA_W(%d)," % flit_w,
            "    .DEPTH(%d)," % fifo_depth,
            "    .STAGES(%d)" % fifo_stages,
            "  ) bridge_%d_fwd (" % i,
            "    .wr_clk(clk_0),",
            "    .wr_rst_n(rst_n_0),",
            "    .wr_en(die0_local_out_valid_%d && ~bridge_%d_fwd_full)," % (r0, i),
            "    .wr_data(die0_local_out_flit_%d)," % r0,
            "    .wr_full(bridge_%d_fwd_full)," % i,
            "    .rd_clk(clk_1),",
            "    .rd_rst_n(rst_n_1),",
            "    .rd_en(bridge_%d_fwd_rd_en)," % i,
            "    .rd_data(bridge_%d_fwd_rd_data)," % i,
            "    .rd_valid(bridge_%d_fwd_rd_valid)," % i,
            "    .rd_empty(bridge_%d_fwd_empty)" % i,
            "  );",
            "  assign die1_local_in_flit_%d = bridge_%d_fwd_rd_data;" % (r1, i),
            "  assign die1_local_in_valid_%d = bridge_%d_fwd_rd_valid;" % (r1, i),
            "  assign bridge_%d_fwd_rd_en = die1_local_in_ready_%d && ~bridge_%d_fwd_empty;" % (i, r1, i),
            "",
            "  // Reverse bridge: die1.router%d -> die0.router%d" % (r1, r0),
            "  logic bridge_%d_rev_full, bridge_%d_rev_rd_en, bridge_%d_rev_rd_valid, bridge_%d_rev_empty;" % (i, i, i, i),
            "  logic [%d:0] bridge_%d_rev_rd_data;" % (flit_w - 1, i),
            "",
            "  cdc_fifo #(",
            "    .DATA_W(%d)," % flit_w,
            "    .DEPTH(%d)," % fifo_depth,
            "    .STAGES(%d)" % fifo_stages,
            "  ) bridge_%d_rev (" % i,
            "    .wr_clk(clk_1),",
            "    .wr_rst_n(rst_n_1),",
            "    .wr_en(die1_local_out_valid_%d && ~bridge_%d_rev_full)," % (r1, i),
            "    .wr_data(die1_local_out_flit_%d)," % r1,
            "    .wr_full(bridge_%d_rev_full)," % i,
            "    .rd_clk(clk_0),",
            "    .rd_rst_n(rst_n_0),",
            "    .rd_en(bridge_%d_rev_rd_en)," % i,
            "    .rd_data(bridge_%d_rev_rd_data)," % i,
            "    .rd_valid(bridge_%d_rev_rd_valid)," % i,
            "    .rd_empty(bridge_%d_rev_empty)" % i,
            "  );",
            "  assign die0_local_in_flit_%d = bridge_%d_rev_rd_data;" % (r0, i),
            "  assign die0_local_in_valid_%d = bridge_%d_rev_rd_valid;" % (r0, i),
            "  assign bridge_%d_rev_rd_en = die0_local_in_ready_%d && ~bridge_%d_rev_empty;" % (i, r0, i),
            "",
        ])

    lines.append("endmodule")
    lines.append("")

    (outdir / "noc_2die.sv").write_text("\n".join(lines))
    return outdir / "noc_2die.sv"


# ── AXI4 wrapper ─────────────────────────────────────────────────────────

def emit_axi4_wrapper(outdir, n_routers):
    """Generate axi4_nic.sv: AXI4 slave interface -> flit injection/ejection."""
    # Use raw string template to avoid f-string conflicts with SystemVerilog
    template = '''// Generated by gen_rtl_2die.py — AXI4 slave NIC
// Converts AXI4 transactions to NoC flits and vice versa.
module axi4_nic #(
  parameter int NUM_ROUTERS = %(n_routers)d,
  parameter int ADDR_W      = 32,
  parameter int DATA_W       = 64,
  parameter int ID_W         = 4,
  parameter int FLIT_W       = 64
) (
  input  logic clk,
  input  logic rst_n,

  // AXI4 slave interface
  input  logic             s_axi_awvalid,
  output logic             s_axi_awready,
  input  logic [ID_W-1:0]  s_axi_awid,
  input  logic [ADDR_W-1:0] s_axi_awaddr,
  input  logic [7:0]       s_axi_awlen,

  input  logic             s_axi_wvalid,
  output logic             s_axi_wready,
  input  logic [DATA_W-1:0] s_axi_wdata,
  input  logic             s_axi_wlast,

  output logic             s_axi_bvalid,
  input  logic             s_axi_bready,
  output logic [ID_W-1:0]  s_axi_bid,
  output logic [1:0]       s_axi_bresp,

  input  logic             s_axi_arvalid,
  output logic             s_axi_arready,
  input  logic [ID_W-1:0]  s_axi_arid,
  input  logic [ADDR_W-1:0] s_axi_araddr,
  input  logic [7:0]       s_axi_arlen,

  output logic             s_axi_rvalid,
  input  logic             s_axi_rready,
  output logic [ID_W-1:0]  s_axi_rid,
  output logic [DATA_W-1:0] s_axi_rdata,
  output logic [1:0]       s_axi_rresp,
  output logic             s_axi_rlast,

  // NoC flit interface
  output logic [FLIT_W-1:0] noc_out_flit,
  output logic       noc_out_valid,
  input  logic       noc_out_ready,
  input  logic [FLIT_W-1:0] noc_in_flit,
  input  logic       noc_in_valid,
  output logic       noc_in_ready
);

  // Address decoding: upper bits = dest router
  function automatic logic [7:0] addr_to_router(
    input logic [ADDR_W-1:0] addr
  );
    return addr[ADDR_W-1:ADDR_W-8];
  endfunction

  // Flit builder
  function automatic logic [FLIT_W-1:0] make_flit(
    input logic [7:0] src, input logic [7:0] dst,
    input logic [39:0] payload
  );
    logic [FLIT_W-1:0] f;
    f = '0;
    f[55:48] = dst;
    f[47:40] = src;
    f[39:0]  = payload;
    return f;
  endfunction

  // State machine
  typedef enum logic [2:0] {
    AXI_IDLE, AXI_WR_DATA, AXI_WR_RESP, AXI_RD_DATA
  } state_t;

  state_t state, state_next;
  logic [ID_W-1:0] axi_id, axi_id_next;
  logic [ADDR_W-1:0] axi_addr, axi_addr_next;
  logic [7:0] axi_len, axi_len_next;
  logic [7:0] axi_beat, axi_beat_next;

  assign s_axi_awready = (state == AXI_IDLE);
  assign s_axi_wready  = (state == AXI_WR_DATA);
  assign s_axi_bvalid  = (state == AXI_WR_RESP);
  assign s_axi_arready = (state == AXI_IDLE);
  assign s_axi_rvalid  = (state == AXI_RD_DATA);

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= AXI_IDLE; axi_id <= '0; axi_addr <= '0;
      axi_len <= '0; axi_beat <= '0;
    end else begin
      state <= state_next; axi_id <= axi_id_next;
      axi_addr <= axi_addr_next; axi_len <= axi_len_next;
      axi_beat <= axi_beat_next;
    end
  end

  always_comb begin
    state_next = state; axi_id_next = axi_id;
    axi_addr_next = axi_addr; axi_len_next = axi_len;
    axi_beat_next = axi_beat;
    noc_out_flit = '0; noc_out_valid = 1'b0; noc_in_ready = 1'b0;
    s_axi_bid = axi_id; s_axi_bresp = 2'b00;
    s_axi_rid = axi_id; s_axi_rdata = '0; s_axi_rresp = 2'b00;
    s_axi_rlast = 1'b0;

    case (state)
      AXI_IDLE: begin
        if (s_axi_awvalid) begin
          axi_id_next = s_axi_awid; axi_addr_next = s_axi_awaddr;
          axi_len_next = s_axi_awlen; axi_beat_next = '0;
          state_next = AXI_WR_DATA;
        end else if (s_axi_arvalid) begin
          axi_id_next = s_axi_arid; axi_addr_next = s_axi_araddr;
          axi_len_next = s_axi_arlen; axi_beat_next = '0;
          state_next = AXI_RD_DATA;
        end
      end
      AXI_WR_DATA: begin
        if (s_axi_wvalid) begin
          noc_out_flit = make_flit(8'd0, addr_to_router(axi_addr),
                                   {32'd0, s_axi_wdata[31:0]});
          noc_out_valid = 1'b1;
          if (noc_out_ready) begin
            axi_beat_next = axi_beat + 1;
            if (s_axi_wlast) state_next = AXI_WR_RESP;
          end
        end
      end
      AXI_WR_RESP: begin
        if (s_axi_bready) state_next = AXI_IDLE;
      end
      AXI_RD_DATA: begin
        noc_in_ready = s_axi_rready;
        if (noc_in_valid) begin
          s_axi_rdata = {32'd0, noc_in_flit[31:0]};
          s_axi_rlast = (axi_beat == axi_len);
          if (s_axi_rready) begin
            axi_beat_next = axi_beat + 1;
            if (axi_beat == axi_len) state_next = AXI_IDLE;
          end
        end
      end
      default: state_next = AXI_IDLE;
    endcase
  end
endmodule
'''
    content = template % {"n_routers": n_routers}
    (outdir / "axi4_nic.sv").write_text(content)
    return outdir / "axi4_nic.sv"


# ── 2-die testbench ───────────────────────────────────────────────────────

def emit_2die_tb(outdir, n_per_die, bridges):
    """Generate tb_2die.sv: testbench for multi-die verification."""
    template = '''// Generated by gen_rtl_2die.py — 2-die testbench
// Sends packets from die0.router0 -> die1.router%(dst_r)d via bridge 0
module tb_2die;
  logic clk_0, clk_1, rst_n_0, rst_n_1;

  // Clock generation (different frequencies for CDC test)
  initial clk_0 = 0;
  always #5 clk_0 = ~clk_0;  // 100 MHz
  initial clk_1 = 0;
  always #7 clk_1 = ~clk_1;  // ~71 MHz (different domain)

  // DUT ports
  noc_pkg::flit_raw_t die0_out_flit [%(n)d-1:0];
  logic       die0_out_valid [%(n)d-1:0];
  logic       die0_out_ready [%(n)d-1:0];
  noc_pkg::flit_raw_t die0_in_flit  [%(n)d-1:0];
  logic       die0_in_valid  [%(n)d-1:0];
  logic       die0_in_ready  [%(n)d-1:0];

  noc_pkg::flit_raw_t die1_out_flit [%(n)d-1:0];
  logic       die1_out_valid [%(n)d-1:0];
  logic       die1_out_ready [%(n)d-1:0];
  noc_pkg::flit_raw_t die1_in_flit  [%(n)d-1:0];
  logic       die1_in_valid  [%(n)d-1:0];
  logic       die1_in_ready  [%(n)d-1:0];

  // Tie ready high (always accept)
  always_comb for (int i = 0; i < %(n)d; i++) begin
    die0_out_ready[i] = 1'b1;
    die1_out_ready[i] = 1'b1;
    die0_in_valid[i]  = 1'b0;
    die0_in_flit[i]   = '0;
    die1_in_valid[i]  = 1'b0;
    die1_in_flit[i]   = '0;
  end

  // DUT instantiation
  noc_2die dut (
    .clk_0(clk_0), .clk_1(clk_1),
    .rst_n_0(rst_n_0), .rst_n_1(rst_n_1),
    // Die 0 ports wired above
    // Die 1 ports wired above
  );

  // Test sequence
  initial begin
    rst_n_0 = 0; rst_n_1 = 0;
    #50;
    rst_n_0 = 1; rst_n_1 = 1;
    #100;

    // Inject flit on die0.router0 -> die1.router%(dst_r)d
    $display("[TB] Injecting cross-die packet via bridge 0");
    die0_in_flit[0] = {1'b0, 8'd0, 8'd0, 8'd%(dst_r)d, 40'hDEAD};
    die0_in_valid[0] = 1'b1;
    @(posedge clk_0);
    die0_in_valid[0] = 1'b0;

    #5000;  // Wait for packet to traverse
    $display("[TB] Simulation complete");
    $finish;
  end

endmodule
'''
    content = template % {"n": n_per_die, "dst_r": bridges[0][1]}
    (outdir / "tb_2die.sv").write_text(content)
    return outdir / "tb_2die.sv"


# ── Main ──────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Extended RTL generator with multi-die + AXI4")
    parser.add_argument("--anynet", required=True, help="Path to .anynet file (2-die topology)")
    parser.add_argument("--outdir", required=True, help="Output directory for generated RTL")
    parser.add_argument("--bridges", type=int, default=8, help="Number of UCIe bridges (default: 8)")
    parser.add_argument("--ucie-latency", type=int, default=10, help="UCIe bridge latency in cycles (default: 10)")
    parser.add_argument("--axi4", action="store_true", help="Also generate AXI4 wrapper")
    parser.add_argument("--n-per-die", type=int, default=64, help="Routers per die (default: 64)")
    args = parser.parse_args()

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    n_per_die = args.n_per_die

    # Parse anynet
    n, adj = parse_anynet(args.anynet)
    print("Parsed anynet: %d nodes, %d edges" % (n, sum(len(v) for v in adj.values()) // 2))

    # Make adjacency symmetric (anynet may have unidirectional links)
    for r in range(n):
        for nb in list(adj[r]):
            if r not in adj[nb]:
                adj[nb].add(r)

    # Split into die0 (0..63) and die1 (64..127)
    adj_die0 = {r: [p for p in adj[r] if p < n_per_die] for r in range(n_per_die)}
    adj_die1 = {r: [p - n_per_die for p in adj[r + n_per_die] if p >= n_per_die]
                for r in range(n_per_die)}

    # Detect bridges from anynet (edges between die0 and die1)
    bridges = []
    for r0 in range(n_per_die):
        for r1_full in adj[r0]:
            if r1_full >= n_per_die:
                r1 = r1_full - n_per_die
                bridges.append((r0, r1, args.ucie_latency))

    print("Die 0: %d routers, %d intra-die edges" % (n_per_die, sum(len(v) for v in adj_die0.values()) // 2))
    print("Die 1: %d routers, %d intra-die edges" % (n_per_die, sum(len(v) for v in adj_die1.values()) // 2))
    print("Bridges: %d UCIe links (%d cyc latency)" % (len(bridges), args.ucie_latency))

    # Generate route tables
    tbl_min_0, tbl_esc_0 = dijkstra_tables(n_per_die, adj_die0), tree_tables(n_per_die, adj_die0)
    tbl_min_1, tbl_esc_1 = dijkstra_tables(n_per_die, adj_die1), tree_tables(n_per_die, adj_die1)

    # Generate files
    print("\nGenerating RTL to %s/" % outdir)

    # 1. noc_pkg.sv
    emit_pkg(outdir, n_per_die, max(len(adj_die0[i]) for i in range(n_per_die)), vcs=4, buf=8, k_block=5)
    print("  noc_pkg.sv")

    # 2. noc_top.sv for each die (same topology, different route tables)
    emit_top(outdir, n_per_die, adj_die0, tbl_min_0, tbl_esc_0, arch="legacy-vc", module_name="noc_top")
    print("  noc_top.sv (die 0 template)")

    # 3. noc_2die.sv
    emit_2die_wrapper(outdir, n_per_die, bridges)
    print("  noc_2die.sv (%d bridges)" % len(bridges))

    # 4. AXI4 wrapper (optional)
    if args.axi4:
        emit_axi4_wrapper(outdir, n_per_die)
        print("  axi4_nic.sv")

    # 5. Testbench
    emit_2die_tb(outdir, n_per_die, bridges)
    print("  tb_2die.sv")

    # 6. Makefile
    emit_makefile(outdir)
    print("  Makefile")

    # 7. Copy cdc_fifo.sv from existing RTL
    cdc_src = Path(__file__).resolve().parent.parent.parent / "rtl" / "cdc" / "cdc_fifo.sv"
    if cdc_src.exists():
        import shutil
        shutil.copy(cdc_src, outdir / "cdc_fifo.sv")
        print("  cdc_fifo.sv (copied from rtl/cdc/)")

    print("\nDone! Build with:")
    print("  cd %s && make" % outdir)
    print("  ./obj_dir/Vnoc_top")


if __name__ == "__main__":
    main()
