// Generated by gen_rtl.py — do not edit
package noc_pkg;
  localparam int N_ROUTERS   = 64;
  localparam int MAX_DEG     = 5;
  localparam int NUM_PORTS   = MAX_DEG + 1;  // +1 local
  localparam int LOCAL_PORT  = MAX_DEG;
  localparam int NUM_VCS     = 2;
  localparam int BUF_DEPTH   = 8;
  localparam int FLIT_W      = 64;
  localparam int DST_W       = 6;
  localparam int TYPE_W      = 2;   // flit type bits [62:61]
  // Flit types (bits [62:61]): HEAD=0 BODY=1 TAIL=2 SINGLE=3
  localparam logic [TYPE_W-1:0] FT_HEAD   = 2'd0;
  localparam logic [TYPE_W-1:0] FT_BODY   = 2'd1;
  localparam logic [TYPE_W-1:0] FT_TAIL   = 2'd2;
  localparam logic [TYPE_W-1:0] FT_SINGLE = 2'd3;
  // Per-PORT credit (shared buffer across VCs), width = clog2(2*BUF_DEPTH+1)
  localparam int CRED_W      = 4;
  // Queue-counter width: must hold 2*BUF_DEPTH (shared 2-VC buffer).
  // A hardcoded 4-bit counter wrapped at 16 while the buffer can hold 16
  // -> silent flit loss (fixed 2026-08-22).
  localparam int QCNT_W      = $clog2(2*8 + 1);
  localparam int PORT_W      = 3;
  localparam int BLOCK_K     = 16;

  typedef struct packed {
    logic [FLIT_W-1:0] raw;   // see layout comment in router.sv:
                              // [63]=esc, [62:61]=type, [DST_W-1+48:48]=dst, [47:0]=src+payload
  } flit_t;

  // Flit wire (raw 64-bit for $readmemh compatibility)
  typedef logic [FLIT_W-1:0] flit_raw_t;
endpackage
